package com.sos.JSHelper.io.Files;

import org.apache.log4j.Logger;

import com.sos.JSHelper.Options.IValueChangedListener;
import com.sos.JSHelper.Options.SOSOptionElement;
import com.sos.JSHelper.Options.SOSValidationError;

/**
* \class SOSProfileEntry 
* 
* \brief SOSProfileEntry - 
* 
* \details
*
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version $Id$
* \see reference
*
* Created on 26.08.2011 20:59:01
 */

/**
 * @author KB
 *
 */
public class SOSProfileEntry extends SOSProfileBaseClass<SOSProfileSection> implements IValueChangedListener {

	@SuppressWarnings("unused")
	private final String		conClassName	= "SOSProfileEntry";
	@SuppressWarnings("unused")
	private static final String	conSVNVersion	= "$Id$";
	private static final Logger	logger			= Logger.getLogger(SOSProfileEntry.class);

	public SOSProfileEntry() {
		//
	}

	public SOSProfileEntry(String pstrEntryName) {
		this(pstrEntryName, "");
	}

	public SOSProfileEntry(String pstrEntryName, String pstrEntryValue) {
		strName = pstrEntryName;
		strValue = pstrEntryValue;
		logger.trace("SOSProfileEntry: " + pstrEntryName + " = " + pstrEntryValue);
	}

	@Override
	public String toString() {
		String strT = "";
		if (strComment != null) {
			strT += strComment.toString();
		}
		strT += strName + "=" + strValue + "\n";
		return strT;
	}

	/**
	 * 
	* \brief toXML - 	
	*
	* \details
	* 
	*
	* @return
	* @param 
	* @author KB
	 */
	public String toXML() {
		String strT = "";
		strT = strT.concat("<" + strName + ">\n");
		strT = strT.concat("<![CDATA[" + strValue + "]]>\n");
		return strT.concat("</" + strName + ">\n");
	}

	/**
	 * 
	* \brief Value - 	
	*
	* \details
	* 
	*
	* @return
	* @author KB
	 */
	public String Value() {
		String strT = strValue;
		return strT;
	}

	/**
	 * 
	* \brief Value - 	
	*
	* \details
	* 
	*
	* @param pstrNewValue
	* @author KB
	 */
	public void Value(String pstrNewValue) {
		if (strValue.equalsIgnoreCase(pstrNewValue) == false) {
			setDirty();
		}
		strValue = pstrNewValue;
	}

	@Override  // IValueChangedListener
	public void ValueHasChanged(final SOSOptionElement pobjOptionElement) {
		this.Value(pobjOptionElement.Value());
	}

	@Override  // IValueChangedListener
	public void ValidationError(SOSValidationError pobjVE) {
		// nothing to do
	}
}
