package com.sos.JSHelper.io.Files;

import java.util.HashMap;
import java.util.Map;

import org.apache.log4j.Logger;

/**
* \class SOSProfileSection 
* 
* \brief SOSProfileSection - 
* 
* \details
*
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version $Id$
* \see reference
*
* Created on 26.08.2011 20:57:21
 */

/**
 * @author KB
 *
 */
public class SOSProfileSection extends SOSProfileBaseClass <JSIniFile> {

	@SuppressWarnings("unused")
	private final String		conClassName	= "SOSProfileSection";
	@SuppressWarnings("unused")
	private static final String	conSVNVersion	= "$Id$";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(SOSProfileSection.class);

	public SOSProfileSection() {
		//
	}

	public Map<String, SOSProfileEntry>	mapProfileEntries;

	public SOSProfileSection(String pstrSectionName) {
		strName = pstrSectionName;
		mapProfileEntries = new HashMap<String, SOSProfileEntry>();
	}

	/**
	 * 
	 * \brief addEntry
	 * 
	 * \details
	 *
	 * \return SOSProfileEntry
	 *
	 * @param pstrEntryName
	 * @param pstrEntryValue
	 * @return
	 */
	public SOSProfileEntry addEntry(String pstrEntryName, String pstrEntryValue) {

		SOSProfileEntry objPE = this.Entry(pstrEntryName);
		if (objPE == null) {
			objPE = new SOSProfileEntry(pstrEntryName, pstrEntryValue);
			objPE.setObjParent(this);
			Map<String, SOSProfileEntry> m = this.Entries();
			m.put(pstrEntryName.toLowerCase(), objPE);
		}
		else {
			objPE.Value(pstrEntryValue);
		}
		return objPE;
	}

	@Override
	public boolean setDirty() {
		this.flgIsDirty = true;
		objParent.setDirty();
		return flgIsDirty;
	}

	public SOSProfileEntry deleteEntry(String pstrEntryName) {

		SOSProfileEntry objPE = this.Entry(pstrEntryName);
		if (objPE == null) {
		}
		else {
			Map<String, SOSProfileEntry> m = this.Entries();
			m.remove(pstrEntryName.toLowerCase());
			setDirty();
		}
		return objPE;
	}

	/**
	 * @return
	 */
	public Map<String, SOSProfileEntry> Entries() {
		if (mapProfileEntries == null) {
			mapProfileEntries = new HashMap<String, SOSProfileEntry>();
		}

		return mapProfileEntries;
	}

	public SOSProfileEntry Entry(String pstrKey) {
		return mapProfileEntries.get(pstrKey.toLowerCase());
	}

	@Override
	public String toString() {
		String strT = "";

		if (strComment != null) {
			strT += strComment.toString();
		}
		strT = strT.concat("[" + strName + "]\n");
		return strT;
	}

	public String toXML() {
		return "";
	}
}
