package com.sos.JSHelper.DataElements;

/**
* \class JSOctalString 
* 
* \brief JSOctalString - 
* 
* \details
*
* \section JSOctalString.java_intro_sec Introduction
*
* \section JSOctalString.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author EQCPN
* @version $Id$03.02.2009
* \see reference
*
* Created on 03.02.2009 15:06:33
 */

public class JSOctalString {

	@SuppressWarnings("unused")
	private final String	conClassName	= "JSOctalString";
	
	private String strOctalString = null;

	public JSOctalString(String pstrOctalString) {
		strOctalString = pstrOctalString;
	}
	
	public boolean isOctal() {
		return JSOctalString.isOctal(strOctalString);
	}
	
	public int toInt() {
		return JSOctalString.toInt(strOctalString);
	}

	public static boolean isOctal(String pOctalString) {
		return (pOctalString.matches("^[0-7]*$")) ? true : false;
	}
	
	public static int toInt(String pOctalString) {
		return isOctal(pOctalString) ? Integer.decode("0"+pOctalString) : 0;
	}
}
