package com.sos.JSHelper.Options;

/**
* \class SOSOptionPasswordTest 
* 
* \brief SOSOptionPasswordTest - 
* 
* \details
*
* \section SOSOptionPasswordTest.java_intro_sec Introduction
*
* \section SOSOptionPasswordTest.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version 20.05.2011
* \see reference
*
* Created on 20.05.2011 16:26:20
 */

import com.sos.JSHelper.io.Files.JSFile;
import org.apache.log4j.Logger;
import org.junit.*;

import java.io.File;
import java.io.IOException;

/**
 * @author KB
 *
 */
public class SOSOptionPasswordTest {

	@SuppressWarnings("unused")
	private final String		conClassName	= "SOSOptionPasswordTest";
	private static final Logger	logger			= Logger.getLogger(SOSOptionPasswordTest.class);
	private SOSOptionPassword objOption = null;

	public SOSOptionPasswordTest() {
		//
	}

	/**
	 * \brief setUpBeforeClass
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	/**
	 * \brief tearDownAfterClass
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	/**
	 * \brief setUp
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@Before
	public void setUp() throws Exception {
		String strLog4JFileName = "./log4j.properties";
		String strT = new File(strLog4JFileName).getAbsolutePath();
		logger.info("logfilename = " + strT);

		objOption = new SOSOptionPassword (null, "key", "Description","value", "DefaultValue", true);

	}

	/**
	 * \brief tearDown
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@After
	public void tearDown() throws Exception {
	}

	/**
	 * Test method for {@link com.sos.JSHelper.Options.SOSOptionPassword#toString()}.
	 */
	@Test
	public final void testToString() {
		objOption.Value("huhu");
		org.junit.Assert.assertEquals("password", "huhu", objOption.Value());
		
		String strFileName = System.getProperty("java.io.tmpdir") + "test.cmd";
		CreateTestFile (strFileName);
		
		objOption.Value(SOSOptionPassword.conBackTic + strFileName + SOSOptionPassword.conBackTic);
		org.junit.Assert.assertEquals("password", "huhu", objOption.Value());
	}

	private void CreateTestFile (final String pstrFileName) {
		

		JSFile objFile = new JSFile(pstrFileName);
		// objFile.deleteOnExit();
		try {
			objFile.WriteLine("@echo off");
			objFile.WriteLine("echo huhu");
			objFile.close();
			objFile.setExecutable(true);
		}
		catch (IOException e) {
			e.printStackTrace();
		}
	}


	/**
	 * Test method for {@link com.sos.JSHelper.Options.SOSOptionPassword#Value()}.
	 */
	@Test
	public final void testValue() {
	}

	/**
	 * Test method for {@link com.sos.JSHelper.Options.SOSOptionPassword#SOSOptionPassword(com.sos.JSHelper.Options.JSOptionsClass, java.lang.String, java.lang.String, java.lang.String, java.lang.String, boolean)}.
	 */
	@Test
	public final void testSOSOptionPassword() {
	}

	/**
	 * Test method for {@link com.sos.JSHelper.Options.SOSOptionPassword#ExecuteCommandToGetPassword()}.
	 */
	@Test
	public final void testExecuteCommandToGetPassword() {
//		fail("Not yet implemented"); // TODO
	}
}
