package sos.scheduler.job;

/**
* \class JobSchedulerSubmitEventProcessAfterMonitor 
* 
* \brief JobSchedulerSubmitEventProcessAfterMonitor - 
* 
* \details
*
* \section JobSchedulerSubmitEventProcessAfterMonitor.java_intro_sec Introduction
*
* \section JobSchedulerSubmitEventProcessAfterMonitor.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 27.01.2012
* \see reference
*
* Created on 27.01.2012 13:42:18
 */

public class JobSchedulerSubmitEventProcessAfterMonitor extends JobSchedulerSubmitEventMonitor {

	@SuppressWarnings("unused")
	private final String	conClassName	= "JobSchedulerSubmitEventProcessAfterMonitor";

	public JobSchedulerSubmitEventProcessAfterMonitor() {
		//
	}
}
