package sos.scheduler.job;

import sos.scheduler.xsl.JobSchedulerXslTransformJSAdapterClass;

/**
* \class SOSXslTransform 
* 
* \brief SOSXslTransform - 
* 
* \details
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 03.08.2011
* \see reference
*
* Created on 03.08.2011 13:51:09
 */

public class SOSXslTransform extends JobSchedulerXslTransformJSAdapterClass {

	@SuppressWarnings("unused")
	private final String	conClassName	= "SOSXslTransform";
	@SuppressWarnings("unused")
	private final String				conSVNVersion		= "$Id$";

	SOSXslTransform() {
		super();
	}
}
