package com.sos.scheduler.model;
/**
* \class SchedulerObjectFactoryTest 
* 
* \brief SchedulerObjectFactoryTest - 
* 
* \details
*
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* @version $Id$20.01.2011
* \see reference
*
* Created on 20.01.2011 11:31:54
 */

import static org.junit.Assert.fail;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.StringReader;
import java.math.BigInteger;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Iterator;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.soap.MessageFactory;
import javax.xml.soap.Name;
import javax.xml.soap.SOAPBody;
import javax.xml.soap.SOAPBodyElement;
import javax.xml.soap.SOAPConnection;
import javax.xml.soap.SOAPConnectionFactory;
import javax.xml.soap.SOAPElement;
import javax.xml.soap.SOAPException;
import javax.xml.soap.SOAPFactory;
import javax.xml.soap.SOAPHeader;
import javax.xml.soap.SOAPMessage;

import org.apache.log4j.Logger;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;
import org.w3c.dom.Document;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;

import com.sos.JSHelper.Basics.JSToolBox;
import com.sos.JSHelper.Exceptions.JobSchedulerException;
import com.sos.JSHelper.Logging.Log4JHelper;
import com.sos.JSHelper.Options.SOSOptionJSTransferMethod.enuJSTransferModes;
import com.sos.scheduler.model.SchedulerObjectFactory.enu4What;
import com.sos.scheduler.model.answers.Answer;
import com.sos.scheduler.model.answers.At;
import com.sos.scheduler.model.answers.Calendar;
import com.sos.scheduler.model.answers.ERROR;
import com.sos.scheduler.model.answers.FileBased;
import com.sos.scheduler.model.answers.Folder;
import com.sos.scheduler.model.answers.Folders;
import com.sos.scheduler.model.answers.HistoryEntry;
import com.sos.scheduler.model.answers.JSCmdBase;
import com.sos.scheduler.model.answers.Job;
import com.sos.scheduler.model.answers.JobChain;
import com.sos.scheduler.model.answers.JobChains;
import com.sos.scheduler.model.answers.Jobs;
import com.sos.scheduler.model.answers.Log;
import com.sos.scheduler.model.answers.Order;
import com.sos.scheduler.model.answers.Orders;
import com.sos.scheduler.model.answers.Period;
import com.sos.scheduler.model.answers.ProcessClass;
import com.sos.scheduler.model.answers.ProcessClasses;
import com.sos.scheduler.model.answers.State;
import com.sos.scheduler.model.answers.Task;
import com.sos.scheduler.model.commands.JSCmdAddJobs;
import com.sos.scheduler.model.commands.JSCmdAddOrder;
import com.sos.scheduler.model.commands.JSCmdJobChainModify;
import com.sos.scheduler.model.commands.JSCmdKillTask;
import com.sos.scheduler.model.commands.JSCmdModifyJob;
import com.sos.scheduler.model.commands.JSCmdModifyOrder;
import com.sos.scheduler.model.commands.JSCmdModifySpooler;
import com.sos.scheduler.model.commands.JSCmdShowCalendar;
import com.sos.scheduler.model.commands.JSCmdShowHistory;
import com.sos.scheduler.model.commands.JSCmdShowJob;
import com.sos.scheduler.model.commands.JSCmdShowJobChain;
import com.sos.scheduler.model.commands.JSCmdShowJobs;
import com.sos.scheduler.model.commands.JSCmdShowState;
import com.sos.scheduler.model.commands.JSCmdShowTask;
import com.sos.scheduler.model.commands.JSCmdStartJob;
import com.sos.scheduler.model.commands.JSCmdSubsystemShow;
import com.sos.scheduler.model.exceptions.JSCommandErrorException;
import com.sos.scheduler.model.exceptions.JSCommandOKException;
import com.sos.scheduler.model.objects.Include;
import com.sos.scheduler.model.objects.JSObjJob;
import com.sos.scheduler.model.objects.JSObjScript;
import com.sos.scheduler.model.objects.Job.Description;
import com.sos.scheduler.model.objects.Params;
import com.sos.scheduler.model.objects.Script;
import com.sos.scheduler.model.objects.Spooler;
import com.sos.scheduler.model.objects.XmlPayload;

/**
 * @author KB
 *
 */
public class SchedulerObjectFactoryTest extends JSToolBox {
	private final String					conClassName				= "SchedulerObjectFactoryTest";
	private static Logger					logger						= Logger.getLogger(SchedulerObjectFactoryTest.class);
	@SuppressWarnings("unused")
	private static Log4JHelper				objLogger					= null;
	private static SchedulerObjectFactory	objSchedulerObjectFactory	= null;

	public SchedulerObjectFactoryTest() {
		super("com_sos_scheduler_model");
		//
	}

	/**
	 * \brief setUpBeforeClass
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@BeforeClass
	// ! [setUpBeforeClass]
	public static void setUpBeforeClass() throws Exception {
		objLogger = new Log4JHelper("./log4j.properties");
		logger = Logger.getRootLogger();
		logger.debug("test start");
		//objSchedulerObjectFactory = new SchedulerObjectFactory("ur.sos", 4139);
		// objSchedulerObjectFactory = new SchedulerObjectFactory("8of9.sos", 4844);
		objSchedulerObjectFactory = new SchedulerObjectFactory("8of9.sos", 4210);
		objSchedulerObjectFactory.initMarshaller(Spooler.class);
	}

	// ! [setUpBeforeClass]

	/**
	 * \brief tearDownAfterClass
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@AfterClass
	public static void tearDownAfterClass() throws Exception {
		objSchedulerObjectFactory.getSocket().doClose();
		logger.debug("test ended");
	}

	/**
	 * \brief setUp
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@Before
	public void setUp() throws Exception {
	}

	/**
	 * \brief tearDown
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @throws java.lang.Exception
	 */
	@After
	public void tearDown() throws Exception {
	}

	@Test
	@Ignore
	public final void testSOAP() throws UnsupportedOperationException, SOAPException, MalformedURLException {

		SOAPConnectionFactory soapConnectionFactory = SOAPConnectionFactory.newInstance();
		SOAPConnection connection = soapConnectionFactory.createConnection();
		SOAPFactory soapFactory = SOAPFactory.newInstance();

		MessageFactory factory = MessageFactory.newInstance();
		SOAPMessage message = factory.createMessage();

		SOAPHeader header = message.getSOAPHeader();
		SOAPBody body = message.getSOAPBody();
		header.detachNode();

		Name bodyName = soapFactory.createName("GetLastTradePrice", "m", "http://wombats.ztrade.com");
		SOAPBodyElement bodyElement = body.addBodyElement(bodyName);

		Name name = soapFactory.createName("symbol");
		SOAPElement symbol = bodyElement.addChildElement(name);
		symbol.addTextNode("SUNW");

		System.out.println(message.toString());
		URL endpoint = new URL("http://wombat.ztrade.com/quotes");
		SOAPMessage response = connection.call(message, endpoint);

		connection.close();

		SOAPBody soapBody = response.getSOAPBody();

		Iterator iterator = soapBody.getChildElements(bodyName);
		bodyElement = (SOAPBodyElement) iterator.next();
		String lastPrice = bodyElement.getValue();

		System.out.print("The last price for SUNW is ");
		System.out.println(lastPrice);

	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createScheduleRemove()}.
	 */
	// @Test
	public final void testCreateScheduleRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createRemoteSchedulerStartRemoteTask()}.
	 */
	// @Test
	public final void testCreateRemoteSchedulerStartRemoteTask() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createKillTask()}.
	 */
	// @Test
	public final void testCreateKillTask() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createSubsystemShow()}.
	 */
	@Test
	// ! [testCreateSubsystemShow]
	public final void testCreateSubsystemShow() {
		JSCmdSubsystemShow objSubsystemShow = objSchedulerObjectFactory.createSubsystemShow();
		objSubsystemShow.setWhat(JSCmdSubsystemShow.enu4What.STATISTICS);
		logger.info(objSubsystemShow.toXMLString());
		objSubsystemShow.run();
		Answer objAnswer = objSubsystemShow.getAnswer();
		String xmlStr = objSchedulerObjectFactory.toXMLString(objAnswer);
		logger.info(xmlStr);
		ERROR objERROR = objAnswer.getERROR();
		if (objERROR != null) {
			throw new JSCommandErrorException(objERROR.getText());
		}
		// TODO objAnswer.getSubsystems fehlt
	}

	// ! [testCreateSubsystemShow]
	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createModifyJob()}.
	 */
	@Test
	// ! [testCreateModifyJob]
	public final void testCreateModifyJob() {
		String jobName = "/junitModel/testStandaloneJob";
		JSCmdModifyJob objModifyJob = objSchedulerObjectFactory.createModifyJob();
		objModifyJob.setJob(jobName);
		objModifyJob.setCmd(JSCmdModifyJob.enu4Cmd.STOP);
		objModifyJob.run();
		try {
			objModifyJob.getAnswerWithException();
		}
		catch (JSCommandOKException e) {
			// TODO objAnswer.getJob() fehlt!
			JSCmdShowJob objShowJob = objSchedulerObjectFactory.createShowJob();
			objShowJob.setJob(jobName);
			objShowJob.setMaxOrders(BigInteger.valueOf(0));
			objShowJob.setMaxTaskHistory(BigInteger.valueOf(0));
			objShowJob.run();
			// Answer objAnswer = objShowJob.getAnswer();
			// if( !objAnswer.getJob().getState().equals("stopped") ) {
			// throw new JobSchedulerException(String.format("$1%s is not stopped even though $2%s was called.", jobName,
			// objModifyJob.toXMLString()));
			// }
			objModifyJob.setCmd(JSCmdModifyJob.enu4Cmd.UNSTOP);
			objModifyJob.run();
			try {
				objModifyJob.getAnswerWithException();
			}
			catch (JSCommandOKException ee) {
				objShowJob.run();
				// objAnswer = objShowJob.getAnswer();
				// if( !objAnswer.getJob().getState().equals("running") ) {
				// throw new JobSchedulerException(String.format("$1%s is not running even though $2%s was called.", jobName,
				// objModifyJob.toXMLString()));
				// }
			}
		}
	}

	// ! [testCreateModifyJob]

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createJobChainModify()}.
	 */
	@Test
	// ! [testCreateJobChainModify]
	public final void testCreateJobChainModify() {
		String jobChainName = "/junitModel/testJobChain";
		JSCmdJobChainModify objModifyJobChain = objSchedulerObjectFactory.createJobChainModify();
		objModifyJobChain.setJobChain(jobChainName);
		objModifyJobChain.setState(JSCmdJobChainModify.enu4State.STOPPED);
		objModifyJobChain.run();
		try {
			objModifyJobChain.getAnswerWithException();
		}
		catch (JSCommandOKException e) {
			// TODO objAnswer.getJobChain() fehlt!
			JSCmdShowJobChain objShowJobChain = objSchedulerObjectFactory.createShowJobChain();
			objShowJobChain.setJobChain(jobChainName);
			objShowJobChain.setMaxOrders(BigInteger.valueOf(0));
			objShowJobChain.setMaxOrderHistory(BigInteger.valueOf(0));
			objShowJobChain.run();
			// Answer objAnswer = objShowJobChain.getAnswer();
			// if( !objAnswer.getJobChain().getState().equals("stopped") ) {
			// throw new JobSchedulerException(String.format("$1%s is not stopped even though $2%s was called.", jobChainName,
			// objModifyJobChain.toXMLString()));
			// }
			objModifyJobChain.setState(JSCmdJobChainModify.enu4State.RUNNING);
			objModifyJobChain.run();
			try {
				objModifyJobChain.getAnswerWithException();
			}
			catch (JSCommandOKException ee) {
				objShowJobChain.run();
				// objAnswer = objShowJobChain.getAnswer();
				// if( !objAnswer.getJobChain().getState().equals("running") ) {
				// throw new JobSchedulerException(String.format("$1%s is not running even though $2%s was called.", jobChainName,
				// objModifyJobChain.toXMLString()));
				// }
			}
		}
	}

	// ! [testCreateJobChainModify]

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createRemoveJobChain()}.
	 */
	// @Test
	public final void testCreateRemoveJobChain() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createProcessClassRemove()}.
	 */
	// @Test
	public final void testCreateProcessClassRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createCheckFolders()}.
	 */
	// @Test
	public final void testCreateCheckFolders() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createModifySpooler()}.
	 */
	// @Test
	public final void testCreateModifySpooler() {
		JSCmdModifySpooler objModifySpooler = objSchedulerObjectFactory.createModifySpooler();
		// objModifySpooler.
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createEventsGet()}.
	 */
	// @Test
	public final void testCreateEventsGet() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createRemoveOrder()}.
	 */
	// @Test
	public final void testCreateRemoveOrder() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createSchedulerLogLogCategoriesReset()}.
	 */
	// @Test
	public final void testCreateSchedulerLogLogCategoriesReset() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createTerminate()}.
	 */
	// @Test
	public final void testCreateTerminate() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createRemoteSchedulerRemoteTaskClose()}.
	 */
	// @Test
	public final void testCreateRemoteSchedulerRemoteTaskClose() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createLockRemove()}.
	 */
	// @Test
	public final void testCreateLockRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createSupervisorRemoteSchedulerConfigurationFetchUpdatedFiles()}.
	 */
	// @Test
	public final void testCreateSupervisorRemoteSchedulerConfigurationFetchUpdatedFiles() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createJobChainNodeModify()}.
	 */
	// @Test
	public final void testCreateJobChainNodeModify() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createModifyOrder()}.
	 */
	// @Test
	public final void testCreateModifyOrder() {
		JSCmdModifyOrder objOrder = objSchedulerObjectFactory.createModifyOrder();
		objOrder.setAt("now");
		objOrder.setOrder("1");
		objOrder.setJobChain("BuildJars");
		objOrder.run();
		Answer objA = objOrder.getAnswer();
		ERROR objE = objA.getERROR();
		if (objE != null) {
			fail("order not started. " + objE.getText());
		}
	}

	// @Test
	public final void testStartOrder() {
		JSCmdModifyOrder objOrder = objSchedulerObjectFactory.StartOrder("BuildJars", "1");
 		try {
			objOrder.getAnswerWithException();
		}
		catch (JSCommandErrorException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			fail(objOrder.getERROR().getText());
		}
		catch (JSCommandOKException e) {
		}
	}

	@Test (expected = JSCommandOKException.class)
	public final void testStartJob() {
		JSCmdStartJob objOrder = objSchedulerObjectFactory.StartJob("/sos/dailyschedule/CheckDaysSchedule");
 		
	}
	 
	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createParamGet()}.
	 */
	// @Test
	public final void testCreateParamGet() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createModifyHotFolder()}.
	 */
	// @Test
	public final void testCreateModifyHotFolder() {
		// fail("Not yet implemented");
	}

	/**
	 * 
	 * \brief testCreateAddJobs
	 * 
	 * \details
	 * This test will add two jobs to the current job scheduler instance.
	 * First job ist a Java-API job and the second is a java-script driven job.
	 * 
	 * There is no checking in job scheduler wether the jobs exists.
	 * If the job already exist it will be overwritten without any further notice.
	 * 
	 * \return void
	 *
	 */
	@Test
	// ! [testCreateAddJobs]
	public final void testCreateAddJobs() {
		// java job
		JSObjJob objJavaJob = objSchedulerObjectFactory.createJob();
		objJavaJob.setName("checkIfWritable");
		objJavaJob.setOrder(false);

		Description objDesc = objSchedulerObjectFactory.createJobDescription();
		Include objDescInclude = objSchedulerObjectFactory.createInclude();
		objDescInclude.setFile("jobs/JobSchedulerCanWrite.xml");
		objDesc.getContent().add(objDescInclude);
		objJavaJob.setDescription(objDesc);

		JSObjScript objScript = objSchedulerObjectFactory.createScript();
		objScript.setLanguage("java");
		objScript.setJavaClass("sos.scheduler.file.JobSchedulerCanWrite");
		objJavaJob.setScript(objScript);

		Params objParams = objSchedulerObjectFactory.setParams(new String[] { "file", "jobs/JobSchedulerCanWrite.xml" });
		objJavaJob.setParams(objParams);

		// javascript job
		JSObjJob objJavaScriptJob = objSchedulerObjectFactory.createJob();
		objJavaScriptJob.setName("hello");
		objJavaScriptJob.setOrder(false);
		JSObjScript objJSScript = objSchedulerObjectFactory.createScript();
		objJSScript.setLanguage("javascript");
		objJSScript.getContent().add("spooler_log.info('hello');");
		objJavaScriptJob.setScript(objJSScript);

		JSCmdAddJobs objAJ = objSchedulerObjectFactory.createAddJobs();
		objAJ.getJob().add(objJavaJob);
		objAJ.getJob().add(objJavaScriptJob);

		logger.debug(objJavaScriptJob.toXMLString());
		
		objAJ.run();
		try {
			objAJ.getAnswerWithException();
		}
		catch (JSCommandOKException e) {
			// TODO: show added jobs
		}
		catch (JSCommandErrorException e) {
			fail(e.getMessage());
		}
	}

	// ! [testCreateAddJobs]

	@Test
	// ! [testCreateAddJobsShort]
	public final void testCreateAddJobsShort() {
		// java job
		JSObjJob objJavaJob = objSchedulerObjectFactory.createStandAloneJob("checkIfWritable");
		Description objDesc = objSchedulerObjectFactory.createJobDescription();
		Include objDescInclude = objSchedulerObjectFactory.createInclude();
		objDescInclude.setFile("jobs/JobSchedulerCanWrite.xml");
		objDesc.getContent().add(objDescInclude);
		objJavaJob.setDescription(objDesc);

		Script objScript = objJavaJob.getScript();
		objScript.setLanguage("java");
		objScript.setJavaClass("sos.scheduler.file.JobSchedulerCanWrite");
		objJavaJob.setScript(objScript);

		Params objParams = objSchedulerObjectFactory.setParams(new String[] { "file", "jobs/JobSchedulerCanWrite.xml" });
		objJavaJob.setParams(objParams);

		// javascript job
		JSObjJob objJavaScriptJob = objSchedulerObjectFactory.createJob();
		objJavaScriptJob.setName("hello");
		objJavaScriptJob.setOrder(false);
		JSObjScript objJSScript = objSchedulerObjectFactory.createScript();
		objJSScript.setLanguage("javascript");
		objJSScript.getContent().add("spooler_log.info('hello');");
		objJavaScriptJob.setScript(objJSScript);

		JSCmdAddJobs objAJ = objSchedulerObjectFactory.createAddJobs();
		objAJ.add(objJavaJob);
		objAJ.add(objJavaScriptJob);

		objAJ.run();
		try {
			objAJ.getAnswerWithException();
		}
		catch (JSCommandOKException e) {
			// TODO: show added jobs
		}
		catch (JSCommandErrorException e) {
			fail(e.getMessage());
		}
	}

	// ! [testCreateAddJobsShort]

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createSchedulerLogLogCategoriesSet()}.
	 */
	// @Test
	public final void testCreateSchedulerLogLogCategoriesSet() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createSpoolerAnswer()}.
	 */
	// @Test
	public final void testCreateSpoolerAnswer() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createLicenceUse()}.
	 */
	// @Test
	public final void testCreateLicenceUse() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#SchedulerObjectFactory()}.
	 */
	// @Test
	public final void testSchedulerObjectFactory() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#run()}.
	 */
	// @Test
	public final void testRun() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#run(com.sos.scheduler.model.answers.JSCmdBase)}.
	 */
	// @Test
	public final void testRunJSCmdBase() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#initMarshaller(java.lang.Class)}.
	 */
	// @Test
	public final void testInitMarshaller() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#unMarshall(java.io.File)}.
	 */
	// @Test
	public final void testUnMarshallFile() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#unMarshall(java.lang.String)}.
	 */
	// @Test
	public final void testUnMarshallString() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#marshal(java.lang.Object, java.io.File)}.
	 */
	// @Test
	public final void testMarshal() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#toXMLString(java.lang.Object)}.
	 */
	// @Test
	public final void testToXMLString() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#Options()}.
	 */
	// @Test
	public final void testOptions() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#SchedulerObjectFactory(java.lang.String, int)}.
	 */
	// @Test
	public final void testSchedulerObjectFactoryStringInt() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#getSocket()}.
	 */
	// @Test
	public final void testGetSocket() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#setParams(java.lang.String[])}.
	 */
	// @Test
	public final void testSetParams() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createParam(java.lang.String, java.lang.String)}.
	 */
	// @Test
	public final void testCreateParamStringString() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createStartJob()}.
	 */
	@Test
	public final void testCreateStartJob() {
		JSCmdStartJob objStartJob = objSchedulerObjectFactory.createStartJob();
		// objStartJob.setName("/junitModel/testStandaloneJob");
		objStartJob.setForce("yes");
		objStartJob.setJob("/junitModel/testStandaloneJob");
		objStartJob.setParams(new String[] { "Hallo", "Value of Hallo" });
		logger.debug(objStartJob.toXMLString());
		try {
			objStartJob.run();
		}
		catch (JobSchedulerException e) {
			fail("Job not started");
		}
		catch (Exception e) {
			fail("Job start results into an exception");
		}
		/**
		 * *
		 * The following xml will the JS respond if the request could be satisfied:
		 * 
					<spooler>
					  <answer time="2011-01-19 11:51:31.352">
					    <ok>
					      <task job="/junitModel/testStandaloneJob" id="3725" task="3725" state="none" name="testStandaloneJob" enqueued="2011-01-19 11:51:31.367" start_at="2011-01-19 11:51:31.352" steps="0" log_file="C:/Program Files (x86)/Scheduler/logs/scheduler-2011-01-19-105244.scheduler.log" force_start="yes">
					        <log level="debug9"/>
					      </task>
					    </ok>
					  </answer>
					</spooler>
		*/
		Task objTask = objStartJob.getTask();
		logger.info("task-id  = " + objTask.getId());
		logger.info("enqueued = " + objTask.getEnqueued());
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createStartJob()}.
	 */
	@Test(expected = JobSchedulerException.class)
	public final void testCreateStartJob1() {
		JSCmdStartJob objStartJob = objSchedulerObjectFactory.createStartJob();
		/*
		 * this shall result into an error because "willi" should not be a valid job
		 */
		objStartJob.setJob("JoeSixpack");
		objStartJob.run();
		/**
		 * This answer is given by the JS in case of an error:
		 * 
		 * <?xml version="1.0" encoding="ISO-8859-1"?>
			<spooler>
			<answer time="2011-01-19 11:51:31.402">
				<ERROR time="2011-01-19 11:51:31" code="SCHEDULER-161" text="SCHEDULER-161  There is no Job '/willi'"/>
			</answer>
			</spooler>
		 */
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowCalendar()}.
	 */
	@Test
	public final void testCreateShowCalendar() {
		JSCmdShowCalendar objSC = objSchedulerObjectFactory.createShowCalendar(); // see: http://localhost:4444/doc/en/xml/show_calendar.xml
		objSC.setWhat("orders");
		objSC.setLimit(9999);
		objSC.setFrom("2011-09-23T00:00:00");
		objSC.setBefore("2011-09-23T23:00:00");
		objSC.run();
		/**
		 * Response should be:
		 * <?xml version="1.0" encoding="ISO-8859-1"?>
		<spooler>
		<answer time="2011-01-20 11:11:42.016">
		<calendar>
		<at at="2011-01-21T11:00:00" job_chain="/FileCopyExampleChain" order="FileCopy1"/>
		<at at="now" job_chain="/SSH/error/CheckJobRun" order="check_job_sample"/>
		</calendar>
		</answer>
		</spooler>
		 */
		Calendar objCalendar = objSC.getCalendar();
		for (Object objCalendarObject : objCalendar.getAtOrPeriod()) {
			if (objCalendarObject instanceof At) {
				At objAt = (At) objCalendarObject;
				// objAt.setParent(objSchedulerObjectFactory);
				// TODO hier gibt es context-probleme, weil die answer nicht im eigentlichen spooler liegt
				// logger.debug(objAt.toXMLString());
				logger.debug(objSchedulerObjectFactory.answerToXMLString(objAt));
				logger.debug("Start at :" + objAt.getAt());
				logger.debug("Job Name :" + objAt.getJob());
				logger.debug("Job-Chain Name :" + objAt.getJobChain());
				logger.debug("Order Name :" + objAt.getOrder());
			}
			else {
				if (objCalendarObject instanceof Period) {
					Period objPeriod = (Period) objCalendarObject;
					// objPeriod.setParent(objSchedulerObjectFactory);
					// logger.debug(objPeriod.toXMLString());
					logger.debug(objSchedulerObjectFactory.answerToXMLString(objPeriod));
					logger.debug("Absolute Repeat Interval :" + objPeriod.getAbsoluteRepeat());
					logger.debug("Timerange start :" + objPeriod.getBegin());
					logger.debug("Timerange end :" + objPeriod.getEnd());
					logger.debug("Job-Name :" + objPeriod.getJob());
				}
			}
		}
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowState()}.
	 */
	@Test
	public final void testCreateShowState() {
		JSCmdShowState objShowState = objSchedulerObjectFactory.createShowState(enu4What.all); // see:
																								// http://localhost:4444/doc/en/xml/show_state.xml
		objShowState.run();
	}

	@Test
	public final void testCreateShowState3() {
		// TODO see JS-612: additional attribute running should be possible to avoid huge xml-response in some installations
		// JSCmdShowState objShowState = objSchedulerObjectFactory.createShowState(new enu4What[] {enu4What.job_chain_jobs,
		// enu4What.running}); // see:
		// http://localhost:4444/doc/en/xml/show_state.xml
		JSCmdShowState objShowState = objSchedulerObjectFactory.createShowState(new enu4What[] { enu4What.job_chain_jobs }); // see:
		// http://localhost:4444/doc/en/xml/show_state.xml
		objShowState.run();
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowState()}.
	 */
	@Test
	public final void testCreateShowState2() {
		JSCmdShowState objShowState = objSchedulerObjectFactory.createShowState(enu4What.remote_schedulers); // see:
		// http://localhost:4444/doc/en/xml/show_state.xml
		objShowState.run();
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowJob()}.
	 */
	@Test
	// ! [testShowJob]
	public final void testShowJob() {
		boolean flgIsJobRunning = false;

		String strJobName = "GenericShellExecutor";
		String strJobChainName = "ShellExecutor";
		String strOrderName = "Execute1";

		int intLastHeartBeatCount = 0;
		String strRegExp = "Antwort von";
		int intTimeBetweenCheck = 11;
		int intMaxNoOfRestarts = 10;

		JSCmdBase.flgRaiseOKException = false;
		JSCmdBase.flgLogXML = false;

		JSCmdShowJob objShowJob = objSchedulerObjectFactory.isJobRunning(strJobName);
		if (objShowJob == null) {
			if (isNotEmpty(strOrderName)) {
				@SuppressWarnings("unused")
				JSCmdModifyOrder objOrder = objSchedulerObjectFactory.StartOrder(strJobChainName, strOrderName);
			}
			else {
				@SuppressWarnings("unused")
				JSCmdStartJob objSJob = objSchedulerObjectFactory.StartJob(strJobName);
			}
			logger.info(String.format("Job '%1$s' was started.", strJobName));
			sleep(intTimeBetweenCheck * 1000); // give JS time to start the job and to get stdout/stderr
		}
		else {
			logger.info(String.format("Job '%1$s' is already running.", strJobName));
		}

		for (int intNoOfRestarts = 0; intNoOfRestarts < intMaxNoOfRestarts;) {
			objShowJob = objSchedulerObjectFactory.isJobRunning(strJobName);
			if (objShowJob == null) { // job is not running ...
				flgIsJobRunning = false;
				JSCmdShowHistory objHist = objSchedulerObjectFactory.createShowHistory();
				objHist.setJob(strJobName);
				objHist.run();
				Answer objHistA = objHist.getAnswer();
				logger.debug(objSchedulerObjectFactory.getLastAnswer());
				List<HistoryEntry> objEntries = objHistA.getHistory().getHistoryEntry();
				if (objEntries != null) {
					HistoryEntry objEntry = objEntries.get(0);
					if (objEntry != null) {
						int intLastExitCode = objEntry.getExitCode().intValue();
						if (intLastExitCode != 0) {
							logger.info(String.format("Exitcode of last Execution was '%1$d'", intLastExitCode));
						}
						else {
							// ExitCode is null
						}
					}
				}
			}
			else { // job is already running ...
				flgIsJobRunning = true;
				Answer objAnswer = objShowJob.getAnswer();
				Job objJobAnswer = objAnswer.getJob();

				int intNoOfTasks = objJobAnswer.getTasks().getCount().intValue();
				logger.debug(String.format("Number of tasks currently running is '%1$d'", intNoOfTasks));
				if (intNoOfTasks > 0) {
					Task objTask = objJobAnswer.getTasks().getTask().get(0);
					if (objTask != null && isNotEmpty(strRegExp)) { // get the heartbeats from the log ...
						Log objTaskLog = objTask.getLog();
						String strT = objTaskLog.getContent();

						// count Heartbeats
						if (isNotEmpty(strRegExp)) { // The JS is getting the stdout/stderr every 10 seconds.
							int intHeartBeatCount = GrepCount(strT, strRegExp);
							if (intHeartBeatCount <= intLastHeartBeatCount) {
								JSCmdKillTask objKiller = objSchedulerObjectFactory.createKillTask();
								objKiller.setId(objTask.getId());
								objKiller.setImmediately("true");
								objKiller.setJob(strJobName);
								objKiller.run();
								logger.info(String.format("Job '%1$s' killed due to missing heartbeats '%2$s'. Count is '%3$d', LastCount was '%4$s'",
										strJobName, strRegExp, intHeartBeatCount, intLastHeartBeatCount));
								// TODO Mail schreiben
							}
							intLastHeartBeatCount = intHeartBeatCount;
						}
					}
				}
				else {
					flgIsJobRunning = false;
				}
			}

			if (flgIsJobRunning == false) {
				if (isNotEmpty(strOrderName)) {
					@SuppressWarnings("unused")
					JSCmdModifyOrder objOrder = objSchedulerObjectFactory.StartOrder(strJobChainName, strOrderName);
				}
				else {
					@SuppressWarnings("unused")
					JSCmdStartJob objSJob = objSchedulerObjectFactory.StartJob(strJobName);
				}
				intNoOfRestarts++;
				logger.info(String.format("Job started again. Number of restarts is '%1$d'", intNoOfRestarts));
				sleep(intTimeBetweenCheck * 1000);
				flgIsJobRunning = true;
				intLastHeartBeatCount = 0;
			}
			else {
				logger.debug(String.format("sleep for 5 seconds, number of restarts is '%1$d'", intNoOfRestarts));
				sleep(intTimeBetweenCheck * 1000);
			}
		} // end for
	}

	private int GrepCount(final String pstrText, final String pstrRegExp) {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::GrepCount";

		Pattern p = Pattern.compile(pstrRegExp);
		BufferedReader buff = new BufferedReader(new StringReader(pstrText));
		int intCount = 0;
		try {
			String a;
			for (a = buff.readLine(); a != null; a = buff.readLine()) {
				Matcher m = p.matcher(a);
				if (m.find()) {
					intCount++;
				}
			}
		}
		catch (IOException e) {
			e.printStackTrace();
		}

		return intCount;
	} // private int GrepCount

	private void sleep(final int pintMillis) {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::sleep";

		try {
			Thread.sleep(pintMillis);
		}
		catch (InterruptedException e) {
		}

	} // private void sleep
		// ! [testShowJob]

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowJobs()}.
	 */
	@Test
	public final void testShowJobs() {
		JSCmdShowJobs objCmdShowJobs = objSchedulerObjectFactory.createShowJobs(enu4What.folders); // http://localhost:4444/doc/en/xml/show_jobs.xml
		objCmdShowJobs.setMaxTaskHistory(BigInteger.valueOf(100));
		objCmdShowJobs.run();
		/**
		 * possible answer
		 * 		
		 *   <job path="/scheduler_file_order_sink" name="scheduler_file_order_sink" job="scheduler_file_order_sink" state="pending" all_steps="0" all_tasks="0" log_file="C:/Program Files (x86)/Scheduler/logs/job.scheduler_file_order_sink.log" order="yes" tasks="1" in_period="yes" job_chain_priority="2" enabled="yes">
		        <file_based state="active">
		          <requisites>
		            <requisite type="Process_class" path=""/>
		          </requisites>
		        </file_based>
		        <tasks count="0"/>
		        <queued_tasks length="0"/>
		        <order_queue length="0"/>
		        <log level="debug9" highest_level="info" last_info="SCHEDULER-893  Job is 'active' now" mail_on_error="yes" mail_on_warning="yes" smtp="smtp.sos" mail_from="scheduler@localhost" mail_to="kb@sos-berlin.com"/>
		     </job>

		 */
		Jobs objJobs = objCmdShowJobs.getJobs();
		for (Job objJob : objJobs.getJob()) {
			logger.debug(String.format("%1$s - %2$s", objJob.getJob(), objJob.getName()));
		}
	}

	@Test
	public final void testShowJobsViaState() {
		JSCmdShowState objCmdShowState = objSchedulerObjectFactory.createShowState(new enu4What[] { enu4What.folders, enu4What.job_chains }); // http://localhost:4444/doc/en/xml/show_state.xml
		objCmdShowState.setMaxTaskHistory(BigInteger.valueOf(100));
		// objCmdShowState.setWhat("folders job_chains no_subfolders");
		objCmdShowState.run();
		State objState = objCmdShowState.getState();
		// TODO hier ist die XML-Structure nicht konsistent. Es beginnt mit Folder und darunter dann (evtl.) Folders.
		// besser ist es, wenn es sofort mit Folders beginnen würde, dann hätte man es leichter die Struktur zu parsen.
		Folder objFolder = objState.getFolder();
		if (objFolder != null) {
			TraverseFolders(objFolder);
		}
		/**
		 * Alle Jobs (und nur die Jobs) mit allen Verzeichnissen:
		 *		<show_state subsystems="folder job" what="folders"/>
		 *
		 * Betreff: what for folder view in show_state
		 *
		 * 		<show_state what="folders job_chains no_subfolders" path="/oh"/>
		 */
	}

	/**
	 * 
	 * \brief TraverseFolders
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @param pobjFolder
	 */
	private void TraverseFolders(final Folder pobjFolder) {
		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::TraverseFolders";
		for (Object objAnObject : pobjFolder.getFileBasedOrJobsOrFolders()) {
			if (objAnObject instanceof FileBased) {
				FileBased objFB = (FileBased) objAnObject;
				logger.debug("file = " + objFB.getFile());
			}
			else
				if (objAnObject instanceof JobChains) {
					JobChains objJobChains = (JobChains) objAnObject;
					for (JobChain objJobChain : objJobChains.getJobChain()) {
						logger.debug(objJobChain.getName());
					}
				}
				else
					if (objAnObject instanceof Jobs) {
						Jobs objJobs = (Jobs) objAnObject;
						for (Job objJob : objJobs.getJob()) {
							logger.debug(objJob.getName());
						}
					}
					else
						if (objAnObject instanceof Folders) {
							Folders objFolders = (Folders) objAnObject;
							for (Folder objFolder : objFolders.getFolder()) {
								TraverseFolders(objFolder);
							}
						}
						else
							if (objAnObject instanceof Orders) {
								Orders objOrders = (Orders) objAnObject;
								for (Order objOrder : objOrders.getOrder()) {
									logger.debug(objOrder.getName());
								}
							}
							else
								if (objAnObject instanceof ProcessClasses) {
									ProcessClasses objProcessClasses = (ProcessClasses) objAnObject;
									for (ProcessClass objProcessClass : objProcessClasses.getProcessClass()) {
										logger.debug(objProcessClass.getName());
									}
								}
		}
	} // private void TraverseFolders

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowTask()}.
	 */
	@Test
	public final void testShowTask() {
		JSCmdShowTask objCmdShowTask = objSchedulerObjectFactory.createShowTask(enu4What.all);
		objCmdShowTask.setId(BigInteger.valueOf(1386758));
		objCmdShowTask.run();
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowOrder()}.
	 */
	// @Test
	public final void testCreateShowOrder() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowJobChain()}.
	 */
	// @Test
	public final void testCreateShowJobChain() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowJobChains()}.
	 */
	// @Test
	public final void testCreateShowJobChains() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.SchedulerObjectFactory#createShowHistory()}.
	 */
	@Test
	public final void testCreateShowHistory() {
		JSCmdShowHistory objCmdShowHistory = objSchedulerObjectFactory.createShowHistory();
		objCmdShowHistory.setJob("/junitModel/testStandaloneJob");
		objCmdShowHistory.setMaxOrders(BigInteger.valueOf(9999));
		// objCmdShowHistory.setId(BigInteger.valueOf(3749));
		// objCmdShowHistory.setWhat("all");
		objCmdShowHistory.run();

	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#ObjectFactory()}.
	 */
	// @Test
	public final void testObjectFactory() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJob()}.
	 */
	// @Test
	public final void testCreateJob() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createParams()}.
	 */
	// @Test
	public final void testCreateParams() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChain()}.
	 */
	// @Test
	public final void testCreateJobChain() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHolidays()}.
	 */
	// @Test
	public final void testCreateHolidays() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createClusterMemberCommand()}.
	 */
	// @Test
	public final void testCreateClusterMemberCommand() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSecurity()}.
	 */
	// @Test
	public final void testCreateSecurity() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRegisterRemoteScheduler()}.
	 */
	// @Test
	public final void testCreateRegisterRemoteScheduler() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSpooler()}.
	 */
	// @Test
	public final void testCreateSpooler() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createServiceRequest()}.
	 */
	// @Test
	public final void testCreateServiceRequest() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createUltimos()}.
	 */
	// @Test
	public final void testCreateUltimos() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createMonthdays()}.
	 */
	// @Test
	public final void testCreateMonthdays() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createWeekdays()}.
	 */
	// @Test
	public final void testCreateWeekdays() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSpoolerConfig()}.
	 */
	// @Test
	public final void testCreateSpoolerConfig() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHolidaysWeekdays()}.
	 */
	// @Test
	public final void testCreateHolidaysWeekdays() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHttpAuthentication()}.
	 */
	// @Test
	public final void testCreateHttpAuthentication() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHttpAuthenticationHttpUsers()}.
	 */
	// @Test
	public final void testCreateHttpAuthenticationHttpUsers() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory()}.
	 */
	@Test
	public final void testCreateOrder() {
		JSCmdAddOrder objOrder = objSchedulerObjectFactory.createAddOrder();
		objOrder.setJobChain("/test/myJobChain");
		// objOrder.setJobChain("BuildJars");
		objOrder.setId("myOrder");
		Params objParams = objSchedulerObjectFactory.setParams(new String[] { "param1", "value1" });
		objOrder.setParams(objParams);
		objOrder.setAt("2012-01-01 01:00:00");
		logger.info(objOrder.toXMLString());
		// objOrder.run();
		// try {
		// objOrder.getAnswerWithException();
		// }
		// catch (JSCommandOKException e) {
		// // TODO: show added order
		// }
		// catch (JSCommandErrorException e) {
		// fail(e.getMessage());
		// }
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRunTime()}.
	 */
	// @Test
	public final void testCreateRunTime() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createEnvironment()}.
	 */
	// @Test
	public final void testCreateEnvironment() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobs()}.
	 */
	// @Test
	public final void testCreateJobs() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobSettings()}.
	 */
	// @Test
	public final void testCreateJobSettings() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobDescription()}.
	 */
	// @Test
	public final void testCreateJobDescription() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobLockUse()}.
	 */
	// @Test
	public final void testCreateJobLockUse() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createParam()}.
	 */
	// @Test
	public final void testCreateParam() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createParamsCopyParams()}.
	 */
	// @Test
	public final void testCreateParamsCopyParams() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createParamsInclude()}.
	 */
	// @Test
	public final void testCreateParamsInclude() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createScript()}.
	 */
	// @Test
	public final void testCreateScript() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createInclude()}.
	 */
	// @Test
	public final void testCreateInclude() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobProcess()}.
	 */
	// @Test
	public final void testCreateJobProcess() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobMonitor()}.
	 */
	// @Test
	public final void testCreateJobMonitor() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobStartWhenDirectoryChanged()}.
	 */
	// @Test
	public final void testCreateJobStartWhenDirectoryChanged() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobDelayAfterError()}.
	 */
	// @Test
	public final void testCreateJobDelayAfterError() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobDelayOrderAfterSetback()}.
	 */
	// @Test
	public final void testCreateJobDelayOrderAfterSetback() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommands()}.
	 */
	// @Test
	public final void testCreateCommands() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createShowJobChains()}.
	 */
	// @Test
	public final void testCreateShowJobChains1() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChains()}.
	 */
	// @Test
	public final void testCreateJobChains() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChainNodeJobChain()}.
	 */
	// @Test
	public final void testCreateJobChainNodeJobChain() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChainNodeEnd()}.
	 */
	// @Test
	public final void testCreateJobChainNodeEnd() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChainFileOrderSource()}.
	 */
	// @Test
	public final void testCreateJobChainFileOrderSource() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChainJobChainNode()}.
	 */
	// @Test
	public final void testCreateJobChainJobChainNode() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createJobChainFileOrderSink()}.
	 */
	// @Test
	public final void testCreateJobChainFileOrderSink() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createPeriod()}.
	 */
	// @Test
	public final void testCreatePeriod() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createShowJobChain()}.
	 */
	// @Test
	public final void testCreateShowJobChain1() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHttpServer()}.
	 */
	// @Test
	public final void testCreateHttpServer() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createWebService()}.
	 */
	// @Test
	public final void testCreateWebService() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHttpDirectory()}.
	 */
	// @Test
	public final void testCreateHttpDirectory() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHoliday()}.
	 */
	// @Test
	public final void testCreateHoliday() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createProcessClass()}.
	 */
	// @Test
	public final void testCreateProcessClass() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createProcessClasses()}.
	 */
	// @Test
	public final void testCreateProcessClasses() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createClusterMemberCommandTerminate()}.
	 */
	// @Test
	public final void testCreateClusterMemberCommandTerminate() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSecurityAllowedHost()}.
	 */
	// @Test
	public final void testCreateSecurityAllowedHost() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createConfigurationFile()}.
	 */
	// @Test
	public final void testCreateConfigurationFile() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createConfigurationDirectory()}.
	 */
	// @Test
	public final void testCreateConfigurationDirectory() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createWebServices()}.
	 */
	// @Test
	public final void testCreateWebServices() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createXmlPayload()}.
	 */
	@Test
	public final void testCreateXmlPayload() throws IOException, SAXException, ParserConfigurationException {
        XmlPayload pl = objSchedulerObjectFactory.createXmlPayload();
            DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
            DocumentBuilder builder = factory.newDocumentBuilder();
            InputSource is = new InputSource( new StringReader( "<Xml_payload><params><param name=\"p1\" value=\"V1\"/><param name=\"p2\" value=\"V2\"/></params></Xml_payload>" ) );
            Document d = builder.parse( is );
            System.out.println(d);
        pl.setAny(d.getDocumentElement());
        logger.info(pl.toXMLString());
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRegisterRemoteSchedulerERROR()}.
	 */
	// @Test
	public final void testCreateRegisterRemoteSchedulerERROR() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createNote()}.
	 */
	// @Test
	public final void testCreateNote() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createLock()}.
	 */
	// @Test
	public final void testCreateLock() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCluster()}.
	 */
	// @Test
	public final void testCreateCluster() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createServiceRequestContent()}.
	 */
	// @Test
	public final void testCreateServiceRequestContent() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSchedulerScript()}.
	 */
	// @Test
	public final void testCreateSchedulerScript() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createUltimosDay()}.
	 */
	// @Test
	public final void testCreateUltimosDay() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createMonthdaysDay()}.
	 */
	// @Test
	public final void testCreateMonthdaysDay() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createMonthdaysWeekday()}.
	 */
	// @Test
	public final void testCreateMonthdaysWeekday() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createWeekdaysDay()}.
	 */
	// @Test
	public final void testCreateWeekdaysDay() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSpoolerConfigBase()}.
	 */
	// @Test
	public final void testCreateSpoolerConfigBase() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSpoolerConfigSchedules()}.
	 */
	// @Test
	public final void testCreateSpoolerConfigSchedules() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSpoolerConfigLocks()}.
	 */
	// @Test
	public final void testCreateSpoolerConfigLocks() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHolidaysWeekdaysDay()}.
	 */
	// @Test
	public final void testCreateHolidaysWeekdaysDay() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createHttpAuthenticationHttpUsersHttpUser()}.
	 */
	// @Test
	public final void testCreateHttpAuthenticationHttpUsersHttpUser() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createOrderPayload()}.
	 */
	// @Test
	public final void testCreateOrderPayload() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRunTimeAt()}.
	 */
	// @Test
	public final void testCreateRunTimeAt() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRunTimeDate()}.
	 */
	// @Test
	public final void testCreateRunTimeDate() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRunTimeMonth()}.
	 */
	// @Test
	public final void testCreateRunTimeMonth() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createEnvironmentVariable()}.
	 */
	// @Test
	public final void testCreateEnvironmentVariable() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsLockRemove(com.sos.scheduler.model.commands.LockRemove)}.
	 */
	// @Test
	public final void testCreateCommandsLockRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsCheckFolders(com.sos.scheduler.model.commands.CheckFolders)}.
	 */
	// @Test
	public final void testCreateCommandsCheckFolders() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsOrder(com.sos.scheduler.model.objects.Order)}.
	 */
	// @Test
	public final void testCreateCommandsOrder() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsProcessClass(com.sos.scheduler.model.objects.ProcessClass)}.
	 */
	// @Test
	public final void testCreateCommandsProcessClass() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsLock(com.sos.scheduler.model.objects.Lock)}.
	 */
	// @Test
	public final void testCreateCommandsLock() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsProcessClassRemove(com.sos.scheduler.model.commands.ProcessClassRemove)}.
	 */
	// @Test
	public final void testCreateCommandsProcessClassRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommandsRunTime(com.sos.scheduler.model.objects.RunTime)}.
	 */
	// @Test
	public final void testCreateCommandsRunTime() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createShowState(com.sos.scheduler.model.commands.ShowState)}.
	 */
	// @Test
	public final void testCreateShowStateShowState() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createScheduleRemove(com.sos.scheduler.model.commands.ScheduleRemove)}.
	 */
	// @Test
	public final void testCreateScheduleRemoveScheduleRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCheckFolders(com.sos.scheduler.model.commands.CheckFolders)}.
	 */
	// @Test
	public final void testCreateCheckFoldersCheckFolders() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSubsystemShow(com.sos.scheduler.model.commands.SubsystemShow)}.
	 */
	// @Test
	public final void testCreateSubsystemShowSubsystemShow() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSchedulerLogLogCategoriesShow(java.lang.Object)}.
	 */
	// @Test
	public final void testCreateSchedulerLogLogCategoriesShow() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createCommands(com.sos.scheduler.model.objects.Commands)}.
	 */
	// @Test
	public final void testCreateCommandsCommands() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createLock(com.sos.scheduler.model.objects.Lock)}.
	 */
	// @Test
	public final void testCreateLockLock() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createParamsGet(java.lang.Object)}.
	 */
	// @Test
	public final void testCreateParamsGet() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createAddOrder(com.sos.scheduler.model.objects.Order)}.
	 */
	@Test
	public final void testCreateAddOrderUsingUDP() {
		JSCmdAddOrder objOrder = objSchedulerObjectFactory.createAddOrder();
		objOrder.setJobChain("scheduler_sosftp_history");
		// objOrder.setId("UdpTestOrder");
		objOrder.setTitle("Test for UDP communication method");
		Params objParams = objSchedulerObjectFactory.setParams(new String[] { "Test1", "Test1", "scheduler_job_chain", "scheduler_sosftp_history" });
		objOrder.setParams(objParams);
		objSchedulerObjectFactory.Options().TransferMethod.Value(enuJSTransferModes.udp.description);
		// objSchedulerObjectFactory.Options().TransferMethod.Value(enuJSTransferModes.tcp.description);
		// objSchedulerObjectFactory.Options().PortNumber.Value("4444");
		// objSchedulerObjectFactory.Options().ServerName.Value("localhost");
		// objOrder.setAt("2012-01-01 01:00:00");
		logger.info(objOrder.toXMLString());
		objOrder.run();
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createLockRemove(com.sos.scheduler.model.commands.LockRemove)}.
	 */
	// @Test
	public final void testCreateLockRemoveLockRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createSchedule(com.sos.scheduler.model.objects.RunTime)}.
	 */
	// @Test
	public final void testCreateSchedule() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createS(com.sos.scheduler.model.commands.ShowState)}.
	 */
	// @Test
	public final void testCreateS() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createOrder(com.sos.scheduler.model.objects.Order)}.
	 */
	// @Test
	public final void testCreateOrderOrder() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createProcessClass(com.sos.scheduler.model.objects.ProcessClass)}.
	 */
	// @Test
	public final void testCreateProcessClassProcessClass() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createShowSchedulers(com.sos.scheduler.model.commands.ShowState)}.
	 */
	// @Test
	public final void testCreateShowSchedulers() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createModifyHotFolder(com.sos.scheduler.model.commands.ModifyHotFolder)}.
	 */
	// @Test
	public final void testCreateModifyHotFolderModifyHotFolder() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createProcessClassRemove(com.sos.scheduler.model.commands.ProcessClassRemove)}.
	 */
	// @Test
	public final void testCreateProcessClassRemoveProcessClassRemove() {
		// fail("Not yet implemented");
	}

	/**
	 * Test method for {@link com.sos.scheduler.model.objects.ObjectFactory#createRunTime(com.sos.scheduler.model.objects.RunTime)}.
	 */
	// @Test
	public final void testCreateRunTimeRunTime() {
		// fail("Not yet implemented");
	}
}
