package com.sos.JSHelper.Basics;



/**
* \class JSJobUtilities
*
* \brief JSJobUtilities -
*
* \details
*
* \section JSJobUtilities.java_intro_sec Introduction
*
* \section JSJobUtilities.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* @version $Id$13.06.2010
* \see reference
*
* Created on 13.06.2010 10:44:14
 */

/**
 * @author KB
 *
 */
public interface JSJobUtilities {

	/**
	 *
	 * \brief myReplaceAll
	 *
	 * \details
	 *
	 * \return String
	 *
	 * @param source
	 * @param what
	 * @param replacement
	 * @return
	 */
	public String myReplaceAll(String source, String what, String replacement) ;
	/**
	 *
	 * \brief replaceSchedulerVars
	 *
	 * \details
	 *
	 * \return String - the modified String
	 *
	 * @param isWindows
	 * @param pstrString2Modify
	 */
	public String replaceSchedulerVars(boolean isWindows, final String pstrString2Modify);

	/**
	 *
	 * \brief setJSParam
	 *
	 * \details
	 *
	 *
	 * @param pstrKey
	 * @param pstrValue
	 * @return
	 */
	public void setJSParam(final String pstrKey, final String pstrValue);
	/**
	 * 
	*
	* \brief setJSParam
	*
	* \details
	* 
	* \return void
	*
	 */
	public void setJSParam(final String pstrKey, final StringBuffer pstrValue);
 
	/**
	 *
	 * \brief getCurrentNodeName
	 *
	 * \details
	 * Returns the the Name of the actual processed Node in a JobChain, if
	 * a Jobchain is to be executed.
	 *
	 * \return String
	 *
	 */
    public String getCurrentNodeName ();

    /**
     * 
    *
    * \brief setJSJobUtilites
    *
    * \details
    * 
    * \return void
    *
     */
	public void setJSJobUtilites (JSJobUtilities pobjJSJobUtilities);
//	/**
//	 *
//	 * \brief setParameters
//	 *
//	 * \details
//	 *
//	 * \return void
//	 *
//	 * @param pVariableSet
//	 */
//	public void setParameters(Variable_set pVariableSet);

	public void setStateText(final String pstrStateText);

	/**
	 * 
	*
	* \brief setCC
	*
	* \details
	* 
	* \return void
	*
	 */
	public void setCC (final int pintCC);
	/**
	 * 
	*
	* \brief setNextNodeState
	*
	* \details
	* 
	* \return void
	*
	 */
	public void setNextNodeState(final String pstrNodeName);

}
