package com.sos.tools.logback.db;

/**
* \class JobnetPlanDBItem 
* 
* \brief JobnetPlanDBItem - 
* 
* \details
*
* \section JobnetPlanDBItem.java_intro_sec Introduction
*
* \section JobnetPlanDBItem.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 23.09.2011
* \see reference
*
* Created on 23.09.2011 15:08:05
 */

import com.sos.hibernate.classes.DbItem;
import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.persistence.*;

@Entity
@Table(name="LOGGING_EVENT_EXCEPTION")
public class LoggingEventExceptionDBItem extends DbItem {

	private static Logger logger = LoggerFactory.getLogger(LoggingEventExceptionDBItem.class);

	 private LoggingEventDBItem loggingEventDBItem = null;
     private Long eventId;
     private Long i;
     private String traceLine;

     private LoggingEventExceptionPK primaryKey;


 	public LoggingEventExceptionDBItem() {
 	   super();
 	}

    @EmbeddedId
    public LoggingEventExceptionPK getPrimaryKey() {
        return primaryKey;
    }

    @EmbeddedId
    public void setPrimaryKey(LoggingEventExceptionPK primaryKey) {
        this.primaryKey = primaryKey;
    }

    @Column(name="EVENT_ID", insertable = false, updatable = false)
    public Long getEventId() {
		return eventId;
	}

    @Column(name="EVENT_ID", insertable = false, updatable = false)
	public void setEventId(Long eventId) {
		this.eventId = eventId;
	}

    @Column(name="I", insertable = false, updatable = false)
    public Long getI() {
		return i;
	}

    @Column(name="I", insertable = false, updatable = false)
	public void setI(Long i) {
		this.i = i;
	}

    @Column(name="TRACE_LINE")
    public String getTraceLine() {
		return traceLine;
	}

    @Column(name="TRACE_LINE")
	public void setTraceLine(String traceLine) {
		this.traceLine = traceLine;
	}

    @ManyToOne (optional=false)
    @NotFound( action = NotFoundAction.EXCEPTION )
    @Cascade(CascadeType.ALL)
    @JoinColumn (name="`EVENT_ID`", insertable = false, updatable = false)
    public LoggingEventDBItem getLoggingEventDBItem() {
        return loggingEventDBItem;
    }
    
    public void setLoggingEventDBItem(LoggingEventDBItem loggingEventDBItem)  {
       this.loggingEventDBItem = loggingEventDBItem;
    }
    
}
