//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.21 at 02:57:11 PM CEST 
//


package com.sos.jobscheduler.tools.webservices.globals.jaxb.SOSCommandSecurityWebserviceAnswer;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sos.jobscheduler.tools.webservices.globals.jaxb.SOSCommandSecurityWebserviceAnswer package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Message_QNAME = new QName("", "message");
    private final static QName _SessionId_QNAME = new QName("", "sessionId");
    private final static QName _Resource_QNAME = new QName("", "resource");
    private final static QName _User_QNAME = new QName("", "user");
    private final static QName _JobSchedulerAnswer_QNAME = new QName("", "jobSchedulerAnswer");
    private final static QName _IsEnabled_QNAME = new QName("", "isEnabled");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sos.jobscheduler.tools.webservices.globals.jaxb.SOSCommandSecurityWebserviceAnswer
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SosSecurityWebserviceAnswer }
     * 
     */
    public SosSecurityWebserviceAnswer createSosCommandSecurityWebserviceJaxbAnswer() {
        return new SosSecurityWebserviceAnswer();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "message")
    public JAXBElement<String> createMessage(String value) {
        return new JAXBElement<String>(_Message_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sessionId")
    public JAXBElement<String> createSessionId(String value) {
        return new JAXBElement<String>(_SessionId_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "resource")
    public JAXBElement<String> createResource(String value) {
        return new JAXBElement<String>(_Resource_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user")
    public JAXBElement<String> createUser(String value) {
        return new JAXBElement<String>(_User_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "jobSchedulerAnswer")
    public JAXBElement<String> createJobSchedulerAnswer(String value) {
        return new JAXBElement<String>(_JobSchedulerAnswer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "isEnabled")
    public JAXBElement<Boolean> createIsEnabled(Boolean value) {
        return new JAXBElement<Boolean>(_IsEnabled_QNAME, Boolean.class, null, value);
    }

}
