package com.sos.scheduler.model.objects;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSObjWebServices 
* 
* \brief JSObjWebServices - 
* 
* \details
*
* \section JSObjWebServices.java_intro_sec Introduction
*
* \section JSObjWebServices.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 09.02.2011 15:25:09
 */

/**
 * @author oh
 *
 */
public class JSObjWebServices extends WebServices {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSObjWebServices";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSObjWebServices.class);

	public JSObjWebServices (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
}
