package com.sos.scheduler.model.objects;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSObjNote 
* 
* \brief JSObjNote - 
* 
* \details
*
* \section JSObjNote.java_intro_sec Introduction
*
* \section JSObjNote.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 09.02.2011 15:00:39
 */

/**
 * @author oh
 *
 */
public class JSObjNote extends Note {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSObjNote";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSObjNote.class);

	public JSObjNote (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
}
