package com.sos.scheduler.model.objects;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSObjConfigurationDirectory 
* 
* \brief JSObjConfigurationDirectory - 
* 
* \details
*
* \section JSObjConfigurationDirectory.java_intro_sec Introduction
*
* \section JSObjConfigurationDirectory.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 09.02.2011 14:26:35
 */

/**
 * @author oh
 *
 */
public class JSObjConfigurationDirectory extends ConfigurationDirectory {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSObjConfigurationDirectory";
	@SuppressWarnings("unused")
	private static final Logger	logger					= Logger.getLogger(JSObjConfigurationDirectory.class);

	public JSObjConfigurationDirectory (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
}
