package com.sos.VirtualFileSystem.common;

import org.apache.log4j.Logger;

import com.sos.i18n.annotation.I18NResourceBundle;

/**
* \class SOSVfsConstants 
* 
* \brief SOSVfsConstants - 
* 
* \details
*
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version $Id$
* \see reference
*
* Created on 25.08.2011 12:42:11
 */

/**
 * @author KB
 *
 */
@I18NResourceBundle(baseName = "SOSVirtualFileSystem", defaultLocale = "en")
public class SOSVfsConstants {

	@SuppressWarnings("unused")
	private final String		conClassName		= "SOSVfsConstants";
	private static final String	conSVNVersion		= "$Id$";
	private static final Logger	logger				= Logger.getLogger(SOSVfsConstants.class);

	public final static String	strBundleBaseName	= "SOSVirtualFileSystem";
	public static String		strVFSLoggerName	= "SOSVfsReportLog";

	public SOSVfsConstants() {
		//
	}
}
