package com.sos.JSHelper.DataElements;

/** \class JSDataElementDateISO
 * 
 * \brief JSDataElementDateISO -
 * 
 * \details Mapics liefert in den CSV-Schnittstellendateien bereits
 * ISO-Datumsangaben. Eine Datumskonvertierung nach XML ist nicht mehr
 * notwendig.
 *
 * \section JSDataElementDateISO.java_intro_sec Introduction
 *
 * \section JSDataElementDateISO.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author EQALS
 * 
 * @version $Id$31.07.2009 \see reference
 *
 *          Created on 31.07.2009 12:28:28 */

public class JSDataElementDateISO extends JSDataElement {

    @SuppressWarnings("unused")
    private final String conClassName = "JSDataElementDateISO";

    public JSDataElementDateISO() {
        //
    }

    public JSDataElementDateISO(String pstrValue) {
        super(pstrValue);
    }

    public JSDataElementDateISO(String pstrValue, String pstrDescription) {
        super(pstrValue, pstrDescription);
    }

    public JSDataElementDateISO(String pstrValue, String pstrDescription, int pintSize, int pintPos, String pstrFormatString, String pstrColumnHeader,
            String pstrXMLTagName) {
        super(pstrValue, pstrDescription, pintSize, pintPos, pstrFormatString, pstrColumnHeader, pstrXMLTagName);
    }

    /** \brief doInit
     *
     * \details
     *
     * \return void */
    @Override
    public void doInit() {
        // super.Size(10);
        super.Description("DateISO");
        super.ColumnHeader("DateISO");
        super.XMLTagName("DateISO");
        // super.setFormatPattern(JSDateFormat.dfDATE_SHORT);
        super.OmitXMLTag(true);

    }
}
