package com.sos.JSHelper.Options;

/**
* \class SOSOptionIniFileName 
* 
* \brief SOSOptionIniFileName - 
* 
* \details
*
* \section SOSOptionIniFileName.java_intro_sec Introduction
*
* \section SOSOptionIniFileName.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* @version $Id$12.07.2010
* \see reference
*
* Created on 12.07.2010 14:25:16
 */

/**
 * @author KB
 *
 */
public class SOSOptionIniFileName extends SOSOptionFileName {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -9066242968890597796L;
	@SuppressWarnings("unused")
	private final String	conClassName	= "SOSOptionIniFileName";

	/**
	 * \brief SOSOptionIniFileName
	 *
	 * \details
	 *
	 * @param pPobjParent
	 * @param pPstrKey
	 * @param pPstrDescription
	 * @param pPstrValue
	 * @param pPstrDefaultValue
	 * @param pPflgIsMandatory
	 */
	public SOSOptionIniFileName(final JSOptionsClass pPobjParent, final String pPstrKey, final String pPstrDescription, final String pPstrValue, final String pPstrDefaultValue,
			final boolean pPflgIsMandatory) {
		super(pPobjParent, pPstrKey, pPstrDescription, pPstrValue, pPstrDefaultValue, pPflgIsMandatory);
		
	}
}
