package com.sos.JSHelper.Options;
import org.apache.log4j.Logger;

/**
* \class SOSOptionArrayList 
* 
* \brief SOSOptionArrayList - 
* 
* \details
*
* \section SOSOptionArrayList.java_intro_sec Introduction
*
* \section SOSOptionArrayList.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version $Id$
* \see reference
*
* Created on 27.04.2011 10:16:23
 */

/**
 * @author KB
 *
 */
public class SOSOptionArrayList extends SOSOptionElement {

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -1909046265576551293L;
	@SuppressWarnings("unused")
	private final String		conClassName	= "SOSOptionArrayList";
	private static final Logger	logger					= Logger.getLogger(SOSOptionArrayList.class);


	/**
	 * \brief SOSOptionArrayList
	 *
	 * \details
	 *
	 * @param pobjParent
	 * @param pstrKey
	 * @param pstrDescription
	 * @param pstrValue
	 * @param pstrDefaultValue
	 * @param pflgIsMandatory
	 */
	public SOSOptionArrayList(final JSOptionsClass pobjParent, final String pstrKey, final String pstrDescription, final String pstrValue, final String pstrDefaultValue,
			final boolean pflgIsMandatory) {
		super(pobjParent, pstrKey, pstrDescription, pstrValue, pstrDefaultValue, pflgIsMandatory);
	}
}
