package com.sos.scheduler.model.commands;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSCmdModifySpooler 
* 
* \brief JSCmdModifySpooler - 
* 
* \details
*
* \section JSCmdModifySpooler.java_intro_sec Introduction
*
* \section JSCmdModifySpooler.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 08.02.2011 14:48:27
 */

/**
 * @author oh
 *
 */
public class JSCmdModifySpooler extends ModifySpooler {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSCmdModifySpooler";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdModifySpooler.class);
	
	public static enum enu4Cmd {
    	PAUSE, 
    	CONTINUE, 
    	RELOAD, 
    	TERMINATE, 
    	TERMINATE_AND_RESTART, 
    	LET_RUN_TERMINATE_AND_RESTART, 
    	ABORT_IMMEDIATELY, 
    	ABORT_IMMEDIATELY_AND_RESTART

		/**/;
		public String Text() {
			String strT = this.name().toLowerCase();
			return strT;
		}
	}

	public JSCmdModifySpooler (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
}
