package com.sos.scheduler.model.commands;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;
import com.sos.scheduler.model.answers.Ok;
import com.sos.scheduler.model.answers.Task;
import com.sos.scheduler.model.objects.Params;

/**
* \class JSCmdStartJob 
* 
* \brief JSCmdStartJob - 
* 
* \details
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* @version $Id$18.01.2011
* \see reference
*
* Created on 18.01.2011 18:28:20
 */

public class JSCmdStartJob extends StartJob {

	private final String		conClassName	= "JSCmdStartJob";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdStartJob.class);

	public JSCmdStartJob(SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}

	/**
	 * 
	 * \brief getTask
	 * 
	 * \details
	 *
	 * \return Task
	 *
	 * @return
	 */
	public Task getTask() {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::getTask";
		Task objTask = null;
		Ok objOK = this.getAnswer().getOk();

		if (objOK != null)
			objTask = objOK.getTask();

		return objTask;
	} // private Task getTask

	/**
	 * 
	 * \brief setParams
	 * 
	 * \details
	 *
	 * \return Params
	 *
	 * @param pstrParamArray
	 * @return
	 */
	public Params setParams(String[] pstrParamArray) {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::setParams";

		Params objParams = objFactory.setParams(pstrParamArray);
		super.setParams(objParams);

		return objParams;
	} // private Params setParams

	// @Override
	// public Object unMarshal(File pobjFile) {
	// return objFactory.unMarshall(pobjFile);
	// }
	//
	// @Override
	// public Object marshal(Object objO, File objF) {
	// return objFactory.marshal(objO, objF);
	// }
	//
	// @Override
	// public String toXMLString(Object objO) {
	// return objFactory.toXMLString(objO);
	// }
	//
	// @Override
	// public String toXMLString() {
	// return objFactory.toXMLString(this);
	// }
	//
	// @Override
	// public void run() {
	// objFactory.run(this);
	// }

	public void setForce(final boolean pflgForce) {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::setForce";

		if (pflgForce) {
			super.setForce("yes");
		}
		else {
			super.setForce("no");
		}

	} // private void setForce
}
