package com.sos.scheduler.model.commands;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;
import com.sos.scheduler.model.SchedulerObjectFactory.enu4What;

/**
* \class JSCmdShowTask 
* 
* \brief JSCmdShowTask - 
* 
* \details
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* @version $Id$18.01.2011
* \see reference
*
* Created on 18.01.2011 18:28:20
 */

public class JSCmdShowTask extends ShowTask {

	private final String		conClassName	= "JSCmdShowTask";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdShowTask.class);

	public JSCmdShowTask(SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
 
	/**
	 * 
	 * \brief setWhat
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @param penuT
	 */
	public void setWhat(enu4What penuT) {
	
	@SuppressWarnings("unused")
	final String	conMethodName	= conClassName + "::setWhat";
	
	super.setWhat(penuT.Text()); 
	
} // private void setWhat

	/**
	 * 
	 * \brief setWhat
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @param penuT
	 */
	public void setWhat(enu4What[] penuT) {
		
		@SuppressWarnings("unused")
		final String	conMethodName	= conClassName + "::setWhat";
		
		String strT = "";
		for (enu4What enuState4What : penuT) {
			strT += enuState4What.Text() + " ";
		}
		super.setWhat(strT); 
		
	} // private JSCmdShowTask setWhat

}
