package sos.ftphistory.db;

/**
* \class TestFtpFilesHistory 
* 
* \brief TestHistorie - 
* 
* \details
*
* \section TestHistorie.java_intro_sec Introduction
*
* \section TestHistorie.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 15.06.2011
* \see reference
*
* Created on 15.06.2011 15:06:50
 */

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.UUID;

import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;
import org.junit.After;
import org.junit.AfterClass;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

//oh 18.04.14 No runnable methods [SP]
@Ignore("Test set to Ignore for later examination")
public class TestJadeFilesHistorie {
 
	private String configurationFilename = "c:/temp/hibernate.cfg.xml";
	private File configurationFile;

	public TestJadeFilesHistorie() {
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
		configurationFile = new File(configurationFilename);
		//jadeFilesDBLayer = new JadeFilesDBLayer(configurationFile);

	}

	@After
	public void tearDown() throws Exception {
	}


 

}
