//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.03.29 at 11:12:34 AM MESZ
//

package sos.scheduler.InstallationService.batchInstallationModel.installations;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/** <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}globals"/>
 *         &lt;element ref="{}installation" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre> */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "globals", "installation" })
@XmlRootElement(name = "installations")
public class Installations {

    @XmlElement(required = true)
    protected Globals globals;
    @XmlElement(required = true)
    protected List<Installation> installation;

    /** Gets the value of the globals property.
     * 
     * @return possible object is {@link Globals } */
    public Globals getGlobals() {
        return globals;
    }

    /** Sets the value of the globals property.
     * 
     * @param value allowed object is {@link Globals } */
    public void setGlobals(Globals value) {
        this.globals = value;
    }

    /** Gets the value of the installation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the installation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getInstallation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Installation } */
    public List<Installation> getInstallation() {
        if (installation == null) {
            installation = new ArrayList<Installation>();
        }
        return this.installation;
    }

}
