package com.sos.JSHelper.Options;


/**
* \class JSOptionIndexedItem 
* 
* \brief JSOptionIndexedItem - 
* 
* \details
*
* \section JSOptionIndexedItem.java_intro_sec Introduction
*
* \section JSOptionIndexedItem.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author EQALS
* @version $Id$19.10.2009
* \see reference
*
* Created on 19.10.2009 10:58:39
 */

public class JSOptionIndexedItem extends SOSOptionElement {

	private final String	conClassName	= "JSOptionIndexedItem";

	protected String[]		strValueList;
	private String			strIndexedKey	= null;

	/**
	 * 
	 * \brief JSOptionIndexedItem
	 *
	 * \details
	 *
	 * @param pPobjParent
	 * @param pPstrKey
	 * @param pPstrDescription
	 * @param pPstrValue
	 * @param pPstrDefaultValue
	 * @param pPflgIsMandatory
	 * @throws Exception 
	 */
	public JSOptionIndexedItem(JSOptionsClass pobjParent, String pstrKey, String pstrDescription, String pstrValue, String pstrDefaultValue,
			boolean pflgIsMandatory) {
		super(pobjParent, pstrKey, pstrDescription, pstrValue, pstrDefaultValue, pflgIsMandatory);
		strIndexedKey = pstrKey;
	}

	public JSOptionIndexedItem(JSOptionsClass pobjParent, String pstrIndexedKey, String pstrDescription, String pstrDefaultValue, boolean pflgIsMandatory)
			throws Exception {
		super(pobjParent, pstrIndexedKey, pstrDescription, null, pstrDefaultValue, pflgIsMandatory);

		strIndexedKey = pstrIndexedKey;
		IndexedKey();
	}

	private void IndexedKey()  {
		if (this.isEmpty(this.strIndexedKey) == false) {
			this.strValueList = objParentClass.getItems(this.strIndexedKey).toArray(new String[0]);
		}
		//		this.strValueList = objValueList.toArray(new String[0]);
		//		this.strValueList = new String[objValueList.size()];

	}

	@Override
	public void MapValue()  {
		IndexedKey();
	}

	/**
	 * 
	 * \brief value - liefert die ValueList als String-Array
	 * 
	 * \details
	 * Diese Methode liefert die ValueList als StringArray.
	 * 
	 * Ein Beispiel:
	 * \code
	 * 			for (int i = 0; i < objVL.value().length; i++) {
	 *				System.out.println (String.format("Index %1$d hat den Wert '%2$s'", i, objVL.ElementAt(i)));
	 *			}
	 * \endcode
	 * 
	 * \return String[] - die ValueList oder eine Liste mit einem leeren Element
	 *
	 * @return
	 */
	public String[] value() {

		@SuppressWarnings("unused")
		final String conMethodName = conClassName + "::value";

		if (this.strValueList == null) {
			this.strValueList = new String[] {  };
		}

		return strValueList;
	} // public String[] value}

	/**
	 * 
	 * \brief AppendValue
	 * 
	 * \details
	 *
	 * \return void
	 *
	 * @param pstrValueList
	 * @throws Exception 
	 */
	public void AddItem(String pstrValue) throws Exception {
//		String strT = pstrValue;

		if (isNotEmpty(pstrValue)) {
			if (this.strValueList == null) {
				this.strValueList = new String[] {};
				super.strValue = pstrValue;
			}
			int intLengthActual = this.strValueList.length;
			String[] strNew = new String[intLengthActual + 1];
			System.arraycopy(strValueList, 0, strNew, 0, intLengthActual);
			strNew[intLengthActual] = pstrValue;
			this.strValueList = strNew;
			//			super.strValue += ";" + pstrValue.replace(";", "");
		}
	}

	@Override
	public boolean IsEmpty() {
		return (this.strValueList == null || this.strValueList.length <= 0);
	}

	/**
	 * 
	 * \brief concatenatedValue
	 * 
	 * \details
	 *
	 * \return String
	 *
	 * @param pstrDelimiter
	 * @return
	 */
	public String concatenatedValue(String pstrDelimiter) {
		StringBuffer strB = new StringBuffer();
		String strT = "";

		if (this.strValueList == null) {
			return strT;
		}
		for (int i = 0; i < this.strValueList.length; i++) {
			strT = this.strValueList[i];
			if (i > 0) {
				if (!this.strValueList[i - 1].trim().endsWith(pstrDelimiter)) {
					strB.append(pstrDelimiter);
				}
			}
			strB.append(strT);
		}
		return strB.toString();
	}

}
