package com.sos.JSHelper.Options;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/** \class SOSOptionJobChainNode
 * 
 * \brief SOSOptionJobChainNode -
 * 
 * \details
 *
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author KB \version $Id$ \see reference
 *
 * Created on 20.08.2011 12:27:14 */

public class SOSOptionJobChainNode extends SOSOptionString {

    private static final long serialVersionUID = 6968731008010049517L;
    @SuppressWarnings("unused")
    private final String conClassName = "SOSOptionJobChainNode";
    private static final String conSVNVersion = "$Id$";
    private static final Logger logger = LoggerFactory.getLogger(SOSOptionJobChainNode.class);

    public SOSOptionJobChainNode(JSOptionsClass pPobjParent, String pPstrKey, String pPstrDescription, String pPstrValue, String pPstrDefaultValue,
            boolean pPflgIsMandatory) {
        super(pPobjParent, pPstrKey, pPstrDescription, pPstrValue, pPstrDefaultValue, pPflgIsMandatory);
        // TODO Auto-generated constructor stub
    }
}
