
/* SOS_JS_CONSUMED_IN_CONDITIONS */
IF NOT EXISTS (SELECT "ID" FROM sysobjects WHERE "ID" = OBJECT_ID(N'SOS_JS_CONSUMED_IN_CONDITIONS'))
  CREATE TABLE SOS_JS_CONSUMED_IN_CONDITIONS (	
    "ID"               NUMERIC(19,0)   IDENTITY(1,1) NOT NULL,
	"SESSION"          VARCHAR(100 BYTE) NOT NULL, 
	"IN_CONDITION_ID"  NUMERIC(19,0) NOT NULL, 
	"CREATED"          DATETIME NOT NULL,
	CONSTRAINT SOS_JS_CONSUMED_IN_CONDITIONS UNIQUE ("SESSION", "IN_CONDITION_ID"),
    PRIMARY KEY ("ID")
   );
SELECT COUNT(*) FROM SOS_JS_CONSUMED_IN_CONDITIONS;
COMMIT;
   
/* SOS_JS_EVENTS */
IF NOT EXISTS (SELECT "ID" FROM sysobjects WHERE "ID" = OBJECT_ID(N'SOS_JS_EVENTS'))
  CREATE TABLE SOS_JS_EVENTS(	
    "ID"              NUMERIC(19,0)   IDENTITY(1,1) NOT NULL,
	"SESSION"         VARCHAR(100 BYTE) NOT NULL, 
	"EVENT"           VARCHAR(255 BYTE) NOT NULL, 
	"WORKFLOW"        VARCHAR(255 BYTE) NOT NULL,
	"CREATED"         DATETIME NOT NULL,
	CONSTRAINT SOS_JS_EVENTS UNIQUE ("SESSION", "EVENT", "WORKFLOW"),
    PRIMARY KEY ("ID")
   );
SELECT COUNT(*) FROM SOS_JS_EVENTS;
COMMIT;

   
/* SOS_JS_IN_CONDITION_COMMANDS */
IF NOT EXISTS (SELECT "ID" FROM sysobjects WHERE "ID" = OBJECT_ID(N'SOS_JS_IN_CONDITION_COMMANDS'))
  CREATE TABLE SOS_JS_IN_CONDITION_COMMANDS (	
    "ID"              NUMERIC(19,0)   IDENTITY(1,1) NOT NULL,
	"IN_CONDITION_ID" NUMERIC(19,0) NOT NULL, 
	"COMMAND"         VARCHAR(255 BYTE) NOT NULL,  
	"COMMAND_PARAM"   VARCHAR(255 BYTE),
    PRIMARY KEY ("ID")
   );
SELECT COUNT(*) FROM SOS_JS_IN_CONDITION_COMMANDS;
COMMIT;

 
/* SOS_JS_IN_CONDITIONS */
IF NOT EXISTS (SELECT "ID" FROM sysobjects WHERE "ID" = OBJECT_ID(N'SOS_JS_IN_CONDITIONS'))
  CREATE TABLE SOS_JS_IN_CONDITIONS (	
    "ID"         NUMERIC(19,0)   IDENTITY(1,1) NOT NULL,
	"MASTER_ID"  VARCHAR(100 BYTE) NOT NULL, 
	"JOB"        VARCHAR(255 BYTE) NOT NULL, 
	"EXPRESSION" VARCHAR(255 BYTE) NOT NULL
	"WORKFLOW"   VARCHAR(255 BYTE) NOT NULL,
    PRIMARY KEY ("ID")
   );
SELECT COUNT(*) FROM SOS_JS_IN_CONDITIONS;
COMMIT;
 
 /* SOS_JS_OUT_CONDITION_EVENTS */
IF NOT EXISTS (SELECT "ID" FROM sysobjects WHERE "ID" = OBJECT_ID(N'SOS_JS_OUT_CONDITION_EVENTS'))
  CREATE TABLE SOS_JS_OUT_CONDITION_EVENTS (
    "ID"               NUMERIC(19,0)   IDENTITY(1,1) NOT NULL,
	"OUT_CONDITION_ID" NUMERIC(19,0) NOT NULL, 
	"EVENT"            VARCHAR(255 BYTE) NOT NULL, 
    PRIMARY KEY ("ID")
   );
SELECT COUNT(*) FROM SOS_JS_OUT_CONDITION_EVENTS;
COMMIT;

   
/* SOS_JS_OUT_CONDITIONS */
IF NOT EXISTS (SELECT "ID" FROM sysobjects WHERE "ID" = OBJECT_ID(N'SOS_JS_OUT_CONDITIONS'))
  CREATE TABLE SOS_JS_OUT_CONDITIONS(
    "ID"         NUMERIC(19,0)   IDENTITY(1,1) NOT NULL,
	"MASTER_ID"  VARCHAR(100 BYTE) NOT NULL, 
	"JOB"        VARCHAR(255 BYTE) NOT NULL, 
	"EXPRESSION" VARCHAR(255 BYTE) NOT NULL,
	"WORKFLOW"   VARCHAR(255 BYTE) NOT NULL,
    PRIMARY KEY ("ID")
   );
SELECT COUNT(*) FROM SOS_JS_OUT_CONDITIONS;
COMMIT;
   