package com.sos.JSHelper.Exceptions;


import com.sos.i18n.annotation.I18NResourceBundle;

/** \class JSNotImplementedException
 * 
 * \brief JSNotImplementedException -
 * 
 * \details
 *
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author KB \version $Id$ \see reference
 *
 * Created on 20.08.2011 11:53:15 */

/** @author KB
 * 
 * @Version $Id$ */
@I18NResourceBundle(baseName = "com_sos_JSHelper_Messages", defaultLocale = "en")
public class JSNotImplementedException extends JobSchedulerException {

    private static final long serialVersionUID = 8821743868485352721L;

    public JSNotImplementedException() {
        super("Function not implemented.");
    }

    /** \brief JSNotImplementedException
     *
     * \details
     *
     * @param pstrMessage */
    public JSNotImplementedException(String pstrMessage) {
        super(pstrMessage);
        // TODO Auto-generated constructor stub
    }

    /** \brief JSNotImplementedException
     *
     * \details
     *
     * @param pstrMessage
     * @param e */
    public JSNotImplementedException(String pstrMessage, Exception e) {
        super(pstrMessage, e);
        // TODO Auto-generated constructor stub
    }
}
