package com.sos.hibernate.classes;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

// import com.sos.hibernate.SOSHibernateConstants;
import com.sos.hibernate.SOSHibernateConstants;
import com.sos.i18n.I18NBase;

/**
* \class Filter 
* 
* \brief Filter - 
* 
* \details
*
* \section Filter.java_intro_sec Introduction
*
* \section Filter.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author Uwe Risse
* \version 24.01.2012
* \see reference
*
* Created on 24.01.2012 12:34:16
 */
public abstract class SOSHibernateFilter extends I18NBase {
	@SuppressWarnings("unused")
	private final String	conClassName	= "Filter";
	private String			sortMode		= "asc";
	private String			orderCriteria;
	private int				limit			= 0;
	protected String		dateFormat		= "yyyy-MM-dd HH:mm:ss";
	protected Date			endTime;
	protected String		status			= "";

	
	 
	
	public String getDateFormat() {
		return dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

	public String getSortMode() {
		if ((orderCriteria == null) || (orderCriteria.equals("")) || (sortMode == null)) {
			return "";
		}
		else {
			return " " + sortMode;
		}
	}

	public void setSortMode(String sortMode) {
		this.sortMode = sortMode;
	}

	public String getOrderCriteria() {
		if ((orderCriteria == null) || (orderCriteria.equals(""))) {
			return "";
		}
		else {
			return " order by " + orderCriteria;
		}
	}

	public void setOrderCriteria(String orderCriteria) {
		this.orderCriteria = orderCriteria;
	}

	public int getLimit() {
		return limit;
	}

	public void setLimit(int limit) {
		this.limit = limit;
	}

	public void setLimit(String limit) {
		try {
			this.limit = Integer.parseInt(limit);
		}
		catch (NumberFormatException e) {
		}
	}

	public String date2Iso(Date d) {
		SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
		String timeIso = formatter.format(d);
		return timeIso;
	}

	public SOSHibernateFilter() {
		super(SOSHibernateConstants.conPropertiesFileName);
	}

	public SOSHibernateFilter(final String strI28NPropertyFileName) {
		super(strI28NPropertyFileName);
	}
	
	
	

}
