//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.01.20 at 02:59:52 PM MEZ
//

package com.sos.scheduler.model.answers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/** <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}at"/>
 *         &lt;element ref="{}period"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre> */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "atOrPeriod" })
@XmlRootElement(name = "calendar")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2011-01-20T02:59:52+01:00", comments = "JAXB RI v2.2.3-hudson-jaxb-ri-2.2.3-3-")
public class Calendar implements Serializable {

    /**
	 * 
	 */
    private static final long serialVersionUID = -8295008771023352341L;
    @XmlElements({ @XmlElement(name = "period", type = Period.class), @XmlElement(name = "at", type = At.class) })
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2011-01-20T02:59:52+01:00", comments = "JAXB RI v2.2.3-hudson-jaxb-ri-2.2.3-3-")
    protected List<Object> atOrPeriod;

    /** Gets the value of the atOrPeriod property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the atOrPeriod property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getAtOrPeriod().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Period }
     * {@link At } */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2011-01-20T02:59:52+01:00", comments = "JAXB RI v2.2.3-hudson-jaxb-ri-2.2.3-3-")
    public List<Object> getAtOrPeriod() {
        if (atOrPeriod == null) {
            atOrPeriod = new ArrayList<Object>();
        }
        return this.atOrPeriod;
    }

}
