/* SOS_JS_CONSUMED_IN_CONDITIONS */
CREATE OR REPLACE FUNCTION tmp() RETURNS VOID AS $$ DECLARE c integer; BEGIN SELECT COUNT(*) INTO c FROM pg_class, pg_namespace, pg_user WHERE UPPER(pg_class.relname) = 'SOS_JS_CON_CONDITIONS_ID_SEQ' AND pg_namespace.oid = pg_class.relnamespace AND pg_class.relowner = pg_user.usesysid and pg_user.usename = current_user; IF c = 0 THEN EXECUTE '
CREATE SEQUENCE SOS_JS_CON_CONDITIONS_ID_SEQ
INCREMENT BY 1 
START WITH 1 
MINVALUE 1 CYCLE;
';
END IF; RETURN; END; $$ LANGUAGE plpgsql;
SELECT tmp();
COMMIT;


CREATE OR REPLACE FUNCTION tmp() RETURNS VOID AS $$ DECLARE c integer; BEGIN SELECT COUNT(*) INTO c FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_CATALOG=CURRENT_DATABASE() AND TABLE_SCHEMA=CURRENT_SCHEMA() AND UPPER(TABLE_NAME)='SOS_JS_CONSUMED_IN_CONDITIONS'; IF c = 0 THEN EXECUTE '

  CREATE TABLE SOS_JS_CONSUMED_IN_CONDITIONS (	
    "ID" BIGINT NOT NULL DEFAULT NEXTVAL(''DAILY_PLAN_ID_SEQ''),
	"SESSION" VARCHAR(100 BYTE) NOT NULL, 
	"IN_CONDITION_ID" BIGINT NOT NULL, 
	"CREATED" TIMESTAMP NOT NULL,
	CONSTRAINT SOS_JS_CONSUMED_IN_CONDITIONS UNIQUE ("SESSION", "IN_CONDITION_ID"),
    PRIMARY KEY ("ID")
   )
';
END IF; RETURN; END; $$ LANGUAGE plpgsql;
SELECT tmp();
COMMIT;
   

  CREATE TABLE SOS_JS_EVENTS(	
    "ID" BIGINT NOT NULL DEFAULT NEXTVAL(''DAILY_PLAN_ID_SEQ''),
	"SESSION" VARCHAR(100 BYTE) NOT NULL, 
	"EVENT" VARCHAR(255 BYTE) NOT NULL, 
	"WORKFLOW" VARCHAR(255 BYTE) NOT NULL,
	"CREATED" TIMESTAMP NOT NULL,
	CONSTRAINT SOS_JS_EVENTS UNIQUE ("SESSION", "EVENT", "WORKFLOW"),
    PRIMARY KEY ("ID")
   )
   

  CREATE TABLE SOS_JS_IN_CONDITION_COMMANDS (	
    "ID" BIGINT NOT NULL DEFAULT NEXTVAL(''DAILY_PLAN_ID_SEQ''),
	"IN_CONDITION_ID" BIGINT NOT NULL, 
	"COMMAND" VARCHAR(255 BYTE) NOT NULL,  
	"COMMAND_PARAM" VARCHAR(255 BYTE),
    PRIMARY KEY ("ID")
   )  
 

  CREATE TABLE SOS_JS_IN_CONDITIONS (	
    "ID" BIGINT NOT NULL DEFAULT NEXTVAL(''DAILY_PLAN_ID_SEQ''),
	"MASTER_ID" VARCHAR(100 BYTE) NOT NULL, 
	"JOB" VARCHAR(255 BYTE) NOT NULL, 
	"EXPRESSION" VARCHAR(255 BYTE) NOT NULL
	"WORKFLOW" VARCHAR(255 BYTE) NOT NULL
    PRIMARY KEY ("ID")
   )
 
 
  CREATE TABLE SOS_JS_OUT_CONDITION_EVENTS (
    "ID" BIGINT NOT NULL DEFAULT NEXTVAL(''DAILY_PLAN_ID_SEQ''),
	"OUT_CONDITION_ID" BIGINT NOT NULL, 
	"EVENT" VARCHAR(255 BYTE) NOT NULL, 
    PRIMARY KEY ("ID")
   )

   

  CREATE TABLE SOS_JS_OUT_CONDITIONS(
    "ID" BIGINT NOT NULL DEFAULT NEXTVAL(''DAILY_PLAN_ID_SEQ''),
	"MASTER_ID" VARCHAR(100 BYTE) NOT NULL, 
	"JOB" VARCHAR(255 BYTE) NOT NULL, 
	"EXPRESSION" VARCHAR(255 BYTE) NOT NULL,
	"WORKFLOW" VARCHAR(255 BYTE) NOT NULL,
    PRIMARY KEY ("ID")
   ) 
   
DROP FUNCTION tmp();
COMMIT;
   
   CREATE SEQUENCE  SOS_JS_CONDITIONS_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  CYCLE ;
   CREATE SEQUENCE  SOS_JS_EVENTS_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 101 CACHE 20 NOORDER  CYCLE ;
   CREATE SEQUENCE  SOS_JS_IN_CONDITION_CMD_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  CYCLE ;
   CREATE SEQUENCE  SOS_JS_IN_CONDITION_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  CYCLE ;
   CREATE SEQUENCE  SOS_JS_OUT_CONDITION_EV_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  CYCLE ;
   CREATE SEQUENCE  SOS_JS_OUT_CONDITION_ID_SEQ  MINVALUE 1 MAXVALUE 999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  CYCLE ;
   



   