set SQL_MODE=ANSI_QUOTES;

/* Table for SOS_JS_CONSUMED_IN_CONDITIONS */
  CREATE TABLE IF NOT EXISTS SOS_JS_CONSUMED_IN_CONDITIONS (	
	"ID"              INT NOT NULL AUTO_INCREMENT, 
	"SESSION"         VARCHAR(100)  CHARACTER SET latin1 NOT NULL, 
	"IN_CONDITION_ID" INT NOT NULL, 
	"CREATED"         DATETIME NOT NULL,
	CONSTRAINT SOS_JS_CONSUMED_IN_CONDITIONS UNIQUE ("SESSION", "IN_CONDITION_ID"),
    INDEX CONDITION_CONSUMED_IN_CONDITION_ID ( "IN_CONDITION_ID" ),
    INDEX CONDITION_CONSUMED_IN_SESSION ( "SESSION" ),
    PRIMARY KEY ("ID")
   ) ENGINE=InnoDB;
   

/* Table for SOS_JS_CONSUMED_IN_CONDITIONS */
  CREATE TABLE IF NOT EXISTS SOS_JS_EVENTS(	
	"ID"               INT NOT NULL AUTO_INCREMENT, 
	"OUT_CONDITION_ID" INT NOT NULL, 
	"SESSION"          VARCHAR(100) CHARACTER SET latin1 NOT NULL, 
	"EVENT"            VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
	"WORKFLOW"         VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
	"CREATED"          DATETIME NOT NULL,
	CONSTRAINT SOS_JS_EVENTS UNIQUE ("SESSION", "EVENT", "WORKFLOW"),
    INDEX CONDITION_OUT_CONDITION_ID ( "OUT_CONDITION_ID" ),
    INDEX CONDITION_EVENT ( "EVENT"),
    INDEX CONDITION_WORKFLOW ( "WORKFLOW"),
    INDEX CONDITION_WORKFLOW ( "SESSION"),
    PRIMARY KEY ("ID")
   ) ENGINE=InnoDB;
   

/* Table for SOS_JS_CONSUMED_IN_CONDITIONS */
  CREATE TABLE IF NOT EXISTS SOS_JS_IN_CONDITION_COMMANDS (	
	"ID"              INT NOT NULL AUTO_INCREMENT, 
	"IN_CONDITION_ID" INT NOT NULL, 
	"COMMAND"         VARCHAR(255) CHARACTER SET latin1 NOT NULL,  
	"COMMAND_PARAM"   VARCHAR(255),
    PRIMARY KEY ("ID")
   ) ENGINE=InnoDB;
 

/* Table for SOS_JS_CONSUMED_IN_CONDITIONS */
  CREATE TABLE IF NOT EXISTS SOS_JS_IN_CONDITIONS (	
	"ID"         INT NOT NULL AUTO_INCREMENT, 
	"MASTER_ID"  VARCHAR(100) CHARACTER SET latin1 NOT NULL, 
	"JOB"        VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
	"WORKFLOW"   VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
	"EXPRESSION" VARCHAR(255) NOT NULL;
    INDEX CONDITION_IN_CONDITION_ID ( "JOB" ),
    INDEX CONDITION_IN_CONDITION_WORKFLOW ( "WORKFLOW" ),
    INDEX CONDITION_IN_CONDITION_MASTER_ID ( "MASTER_ID" ),
    PRIMARY KEY ("ID")
   ) ENGINE=InnoDB;
 
 
/* Table for SOS_JS_CONSUMED_IN_CONDITIONS */
  CREATE TABLE IF NOT EXISTS SOS_JS_OUT_CONDITION_EVENTS (
	"ID"               INT NOT NULL AUTO_INCREMENT, 
	"OUT_CONDITION_ID" INT NOT NULL, 
	"EVENT"            VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
    INDEX CONDITION_OUT_CONDITION_OUT_CONDITION_ID ( "OUT_CONDITION_ID" ),
    PRIMARY KEY ("ID")
   ) ENGINE=InnoDB;

   

/* Table for SOS_JS_CONSUMED_IN_CONDITIONS */
  CREATE TABLE IF NOT EXISTS SOS_JS_OUT_CONDITIONS(
	"ID"         INT NOT NULL AUTO_INCREMENT, 
	"MASTER_ID"  VARCHAR(100) CHARACTER SET latin1 NOT NULL, 
	"JOB"        VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
	"WORKFLOW"   VARCHAR(255) CHARACTER SET latin1 NOT NULL, 
	"EXPRESSION" VARCHAR(255) CHARACTER SET latin1 NOT NULL,
    INDEX CONDITION_OUT_CONDITIONS_OUT_MASTER_ID ( "MASTER_ID" ),
    INDEX CONDITION_OUT_CONDITIONS_OUT_JOB ("JOB"),
    INDEX CONDITION_OUT_CONDITIONS_OUT_WORKFLOW ("WORKFLOW"),
    PRIMARY KEY ("ID")
   ) ENGINE=InnoDB;
   
    