package com.sos.scheduler.model.commands;

import javax.xml.bind.JAXBElement;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;
import com.sos.scheduler.model.objects.JSObjBase;

/**
* \class JSCmdSubsystemShow 
* 
* \brief JSCmdSubsystemShow - 
* 
* \details
*
* \section JSCmdSubsystemShow.java_intro_sec Introduction
*
* \section JSCmdSubsystemShow.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 08.02.2011 16:24:56
 */

/**
 * @author oh
 *
 */
public class JSCmdSubsystemShow extends SubsystemShow {

	private final String		conClassName	= "JSCmdSubsystemShow";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdSubsystemShow.class);
	
	public enum enu4What {
    	STATISTICS
    	/**/;
		public String Text() {
			String strT = this.name().toLowerCase();
			return strT;
		}
	}

	@SuppressWarnings("unchecked")
	public JSCmdSubsystemShow (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
		objJAXBElement = (JAXBElement<JSObjBase>) unMarshal("<subsystem.show/>");
		setObjectFieldsFrom((SubsystemShow) objJAXBElement.getValue());
	}
	
	/**
	 * 
	 * \brief setWhat
	 * 
	 * \details
	 *
	 * @param penuT
	 */
	public void setWhat(enu4What penuT) {
	
		@SuppressWarnings("unused")
		final String	conMethodName	= conClassName + "::setWhat";
	
		super.setWhat(penuT.Text()); 
	
	} // public void setWhat

	/**
	 * 
	 * \brief setWhat
	 * 
	 * \details
	 *
	 * @param penuT
	 */
	public void setWhat(enu4What[] penuT) {
		
		@SuppressWarnings("unused")
		final String	conMethodName	= conClassName + "::setWhat";
		
		String strT = "";
		for (enu4What enuState4What : penuT) {
			strT += enuState4What.Text() + " ";
		}
		super.setWhat(strT); 
		
	} // public void setWhat
	
}
