package com.sos.scheduler.model.commands;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSCmdModifyHotFolder 
* 
* \brief JSCmdModifyHotFolder - 
* 
* \details
*
* \section JSCmdModifyHotFolder.java_intro_sec Introduction
*
* \section JSCmdModifyHotFolder.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 08.02.2011 14:38:22
 */

/**
 * @author oh
 *
 */
public class JSCmdModifyHotFolder extends ModifyHotFolder {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSCmdModifyHotFolder";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdModifyHotFolder.class);

	public JSCmdModifyHotFolder (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
}
