package com.sos.scheduler.model.commands;

import com.sos.scheduler.model.SchedulerObjectFactory;
import com.sos.scheduler.model.objects.JSObjCommands;
import org.apache.log4j.Logger;

/**
* \class JSCmdAddOrder 
* 
* \brief JSCmdAddOrder - 
* 
* \details
*
* \section JSCmdAddOrder.java_intro_sec Introduction
*
* \section JSCmdAddOrder.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 04.03.2011 12:29:11
 */

/**
 * @author ss
 *
 */
public class JSCmdCommands extends JSObjCommands {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSCmdCommands";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSCmdCommands.class);

	public JSCmdCommands(SchedulerObjectFactory schedulerObjectFactory) {
		super(schedulerObjectFactory);
	}

}
