package com.sos.VirtualFileSystem.Interfaces;

/**
* \class ISOSSession 
* 
* \brief ISOSSession - 
* 
* \details
*
* \section ISOSSession.java_intro_sec Introduction
*
* \section ISOSSession.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* @version $Id$21.05.2010
* \see reference
*
* Created on 21.05.2010 10:58:59
 */

/**
 * @author KB
 *
 */
public interface ISOSSession {

	public ISOSSession OpenSession (ISOSShellOptions pobjShellOptions) throws Exception;
	public void CloseSession () throws Exception;
	
}
