//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3-
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2011.01.17 at 03:00:56 PM MEZ
//

package com.sos.scheduler.model.objects;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/** <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="http.authentication" type="{}http.authentication"/>
 *         &lt;element name="web_service" type="{}web_service"/>
 *         &lt;element name="http_directory" type="{}http_directory"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre> */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "httpAuthenticationOrWebServiceOrHttpDirectory" })
@XmlRootElement(name = "http_server")
public class HttpServer extends JSObjBase {

    @XmlElements({ @XmlElement(name = "web_service", type = WebService.class), @XmlElement(name = "http_directory", type = HttpDirectory.class),
            @XmlElement(name = "http.authentication", type = HttpAuthentication.class) })
    protected List<Object> httpAuthenticationOrWebServiceOrHttpDirectory;

    /** Gets the value of the httpAuthenticationOrWebServiceOrHttpDirectory
     * property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a
     * snapshot. Therefore any modification you make to the returned list will
     * be present inside the JAXB object. This is why there is not a
     * <CODE>set</CODE> method for the
     * httpAuthenticationOrWebServiceOrHttpDirectory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getHttpAuthenticationOrWebServiceOrHttpDirectory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WebService } {@link HttpDirectory } {@link HttpAuthentication } */
    public List<Object> getHttpAuthenticationOrWebServiceOrHttpDirectory() {
        if (httpAuthenticationOrWebServiceOrHttpDirectory == null) {
            httpAuthenticationOrWebServiceOrHttpDirectory = new ArrayList<Object>();
        }
        return this.httpAuthenticationOrWebServiceOrHttpDirectory;
    }

}
