package com.sos.scheduler.model.objects;

import com.sos.JSHelper.Exceptions.JobSchedulerException;
import com.sos.scheduler.model.SchedulerObjectFactory;
import org.apache.log4j.Logger;

/** \class JSObjXmlPayload
 * 
 * \brief JSObjXmlPayload -
 * 
 * \details
 *
 * \section JSObjXmlPayload.java_intro_sec Introduction
 *
 * \section JSObjXmlPayload.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author oh
 * 
 * @version $Id$ \see reference
 *
 *          Created on 09.02.2011 15:24:01 */

/** @author oh */
public class JSObjXmlPayload extends XmlPayload {

    @SuppressWarnings("unused")
    private final String conClassName = "JSObjXmlPayload";
    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(JSObjXmlPayload.class);

    public JSObjXmlPayload(SchedulerObjectFactory schedulerObjectFactory) {
        super();
        try {
            objFactory = schedulerObjectFactory;
            // objJAXBElement = (JAXBElement<JSObjBase>) unMarshal("");
            // setObjectFieldsFrom(objJAXBElement.getValue());
        } catch (Exception e) {
            logger.error("Could not instantiate Order.", e);
            throw new JobSchedulerException("Could not instantiate Payload.", e);
        }
        objFactory = schedulerObjectFactory;
    }

}
