package com.sos.scheduler.model.objects;

import com.sos.scheduler.model.SchedulerObjectFactory;

/** \class JSObjRegisterRemoteScheduler
 * 
 * \brief JSObjRegisterRemoteScheduler -
 * 
 * \details
 *
 * \section JSObjRegisterRemoteScheduler.java_intro_sec Introduction
 *
 * \section JSObjRegisterRemoteScheduler.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author oh
 * 
 * @version $Id$ \see reference
 *
 *          Created on 09.02.2011 15:14:43 */

/** @author oh */
public class JSObjRegisterRemoteScheduler extends RegisterRemoteScheduler {

    @SuppressWarnings("unused")
    private final String conClassName = "JSObjRegisterRemoteScheduler";

    public JSObjRegisterRemoteScheduler(SchedulerObjectFactory schedulerObjectFactory) {
        super();
        objFactory = schedulerObjectFactory;
    }
}
