package com.sos.scheduler.model.objects;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/** \class JSObjJobChainNodeJobChain
 * 
 * \brief JSObjJobChainNodeJobChain -
 * 
 * \details
 *
 * \section JSObjJobChainNodeJobChain.java_intro_sec Introduction
 *
 * \section JSObjJobChainNodeJobChain.java_samples Some Samples
 *
 * \code .... code goes here ... \endcode
 *
 * <p style="text-align:center">
 * <br />
 * --------------------------------------------------------------------------- <br />
 * APL/Software GmbH - Berlin <br />
 * ##### generated by ClaviusXPress (http://www.sos-berlin.com) ######### <br />
 * ---------------------------------------------------------------------------
 * </p>
 * \author oh
 * 
 * @version $Id$ \see reference
 *
 *          Created on 09.02.2011 14:42:15 */

/** @author oh */
public class JSObjJobChainNodeJobChain extends JobChainNodeJobChain {

    @SuppressWarnings("unused")
    private final String conClassName = "JSObjJobChainNodeJobChain";
    @SuppressWarnings("unused")
    private static final Logger logger = Logger.getLogger(JSObjJobChainNodeJobChain.class);

    public JSObjJobChainNodeJobChain(SchedulerObjectFactory schedulerObjectFactory) {
        super();
        objFactory = schedulerObjectFactory;
    }

}
