package com.sos.scheduler.model.objects;

import org.apache.log4j.Logger;

import com.sos.scheduler.model.SchedulerObjectFactory;

/**
* \class JSObjSecurity 
* 
* \brief JSObjSecurity - 
* 
* \details
*
* \section JSObjSecurity.java_intro_sec Introduction
*
* \section JSObjSecurity.java_samples Some Samples
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author oh
* @version $Id$
* \see reference
*
* Created on 08.02.2011 01:54:28
 */

/**
 * @author oh
 *
 */
public class JSObjSecurity extends Security {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSObjSecurity";
	@SuppressWarnings("unused")
	private static final Logger	logger			= Logger.getLogger(JSObjSecurity.class);

	public JSObjSecurity (SchedulerObjectFactory schedulerObjectFactory) {
		super();
		objFactory = schedulerObjectFactory;
	}
}
