//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.3-hudson-jaxb-ri-2.2.3-3- 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.01.17 at 03:00:56 PM MEZ 
//
package com.sos.scheduler.model.objects;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}include"/>
 *       &lt;/choice>
 *       &lt;attribute name="language" type="{}Name" />
 *       &lt;attribute name="use_engine">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="task"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="com_class" type="{}String" />
 *       &lt;attribute name="filename" type="{}File" />
 *       &lt;attribute name="java_class" type="{}String" />
 *       &lt;attribute name="java_class_path" type="{}String" />
 *       &lt;attribute name="recompile" type="{}Yes_no" />
 *       &lt;attribute name="encoding" type="{}Code_page_encoding" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "content" })
@XmlRootElement(name = "script")
public class Script extends JSObjBase {
	@XmlElementRef(name = "include", type = Include.class)
	@XmlMixed
	protected List<Object>		content;
//	protected String		content;

	@XmlAttribute(name = "language")
	protected String			language;
	@XmlAttribute(name = "use_engine")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String			useEngine;
	@XmlAttribute(name = "com_class")
	protected String			comClass;
	@XmlAttribute(name = "filename")
	protected String			filename;
	@XmlAttribute(name = "java_class")
	protected String			javaClass;
	@XmlAttribute(name = "java_class_path")
	protected String			javaClassPath;
	@XmlAttribute(name = "recompile")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	protected String			recompile;
	@XmlAttribute(name = "encoding")
	protected CodePageEncoding	encoding;

	/**
	 * Gets the value of the content property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the content property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getContent().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link Include }
	 * {@link String }
	 * 
	 * 
	 */
	public List<Object> getContent() {
		if (content == null) {
			content = new ArrayList<Object>();
		}
		return this.content;
	}

//	public void setContent (final String pstrS) {
//		this.content = pstrS;
//	}
//	public String getContent() {
//		if (content == null) {
//			content = "";
//		}
//		return this.content;
//	}

	/**
	 * Gets the value of the language property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getLanguage() {
		return language;
	}

	/**
	 * Sets the value of the language property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setLanguage(String value) {
		this.language = value;
	}

	/**
	 * Gets the value of the useEngine property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getUseEngine() {
		return useEngine;
	}

	/**
	 * Sets the value of the useEngine property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setUseEngine(String value) {
		this.useEngine = value;
	}

	/**
	 * Gets the value of the comClass property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getComClass() {
		return comClass;
	}

	/**
	 * Sets the value of the comClass property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setComClass(String value) {
		this.comClass = value;
	}

	/**
	 * Gets the value of the filename property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getFilename() {
		return filename;
	}

	/**
	 * Sets the value of the filename property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setFilename(String value) {
		this.filename = value;
	}

	/**
	 * Gets the value of the javaClass property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getJavaClass() {
		return javaClass;
	}

	public String getJavaClassPath() {
		return javaClassPath;
	}

	/**
	 * Sets the value of the javaClass property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setJavaClass(String value) {
		this.javaClass = value;
	}

	public void setJavaClassPath(String value) {
		this.javaClassPath = value;
	}

	/**
	 * Gets the value of the recompile property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link String }
	 *     
	 */
	public String getRecompile() {
		return recompile;
	}

	/**
	 * Sets the value of the recompile property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link String }
	 *     
	 */
	public void setRecompile(String value) {
		this.recompile = value;
	}

	/**
	 * Gets the value of the encoding property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link CodePageEncoding }
	 *     
	 */
	public CodePageEncoding getEncoding() {
		return encoding;
	}

	/**
	 * Sets the value of the encoding property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link CodePageEncoding }
	 *     
	 */
	public void setEncoding(CodePageEncoding value) {
		this.encoding = value;
	}
}
