package sos.scheduler.file;

import org.apache.log4j.Logger;
import org.junit.*;

/**
* \class JSFolderSyncTest 
* 
* \brief JSFolderSyncTest - 
* 
* \details
*
*
* \code
*   .... code goes here ...
* \endcode
*
* <p style="text-align:center">
* <br />---------------------------------------------------------------------------
* <br /> APL/Software GmbH - Berlin
* <br />##### generated by ClaviusXPress (http://www.sos-berlin.com) #########
* <br />---------------------------------------------------------------------------
* </p>
* \author KB
* \version $Id$
* \see reference
*
* Created on 19.08.2011 16:10:13
 */

public class JSFolderSyncTest  {

	@SuppressWarnings("unused")
	private final String		conClassName	= "JSFolderSyncTest";
	private static final String	conSVNVersion	= "$Id$";
	private static final Logger	logger			= Logger.getLogger(JSFolderSyncTest.class);

	private JSExistsFileOptions objO = null;
	private JSFolderSync objSync = null;

	public JSFolderSyncTest() {
		//
	}

	@BeforeClass
	public static void setUpBeforeClass() throws Exception {
	}

	@AfterClass
	public static void tearDownAfterClass() throws Exception {
	}

	@Before
	public void setUp() throws Exception {
		objSync = new JSFolderSync ();
		objO = objSync.Options();
	}

	@After
	public void tearDown() throws Exception {
	}

	@Test
  @Ignore("Test set to Ignore for later examination")
	public void Execute1Test () {
		objO.file.Value("c:/temp/bin/");
		objO.file_spec.Value(".*");
		objO.target.Value("c:/temp/bin-sync");
		
		objSync.Execute();
	}

	@Test (expected=com.sos.JSHelper.Exceptions.JobSchedulerException.class) 
  @Ignore("Test set to Ignore for later examination")
	public void JFO_F_0100Test () {
		objO.skip_first_files.value(-2);
		objO.skip_last_files.value(2);
		objSync.Execute();
	}
	
	@Test (expected=com.sos.JSHelper.Exceptions.JobSchedulerException.class) 
  @Ignore("Test set to Ignore for later examination")
	public void JFO_F_0101Test () {
		objO.skip_first_files.value(2);
		objO.skip_last_files.value(2);
		objSync.Execute();
	}
	
	@Test (expected=com.sos.JSHelper.Exceptions.JobSchedulerException.class) 
	@Ignore("Test set to Ignore for later examination, fails in Jenkins build")
	public void JFO_F_0102Test () {
		objO.file_spec.Value("[date:heute]");
		objSync.Execute();
	}
	
	@Test (expected=com.sos.JSHelper.Exceptions.JobSchedulerException.class) 
	@Ignore("Test set to Ignore for later examination")
	public void JFO_F_0103Test () {
		objO.skip_first_files.value(2);
		objSync.Execute();
	}
}
