package com.sos.JSHelper.Logging;
/**
 * \package com.sos.JSHelper.Logging
 * \brief 
 * Klassen zur Implementierung/Erweiterung des log4J-Api.
 *
 * \detail
 * Die Klassen dieses Packages werden für das Logging verwendet. 
 * Ihr Verhalten wird mit einem Property-File gesteuert.
 * 
 *
 * <div class="sos_branding">
 *   <p>© 2009 APL/Software GmbH - Berlin - generated by ClaviusXPress (<a style="color:silver" href="http://www.sos-berlin.com" target="_blank">http://www.sos-berlin.com</a>)</p>
 * </div>
 */

